begin;
create extension if not exists pgtap with schema extensions;
set local search_path=extensions,public;
select plan(13);
insert into auth.users(id,email,email_confirmed_at) values ('e1630000-0000-4000-8000-000000000001','deletion-163@example.invalid',now()),('e1630000-0000-4000-8000-000000000002','other-163@example.invalid',now());
select ok(not has_table_privilege('authenticated','private.account_deletion_requests','SELECT'),'request table is private');
select ok(not has_function_privilege('anon','public.request_account_deletion(boolean)','EXECUTE'),'anonymous caller cannot request');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"e1630000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok('select public.request_account_deletion(false)','22023','confirmation_required','explicit confirmation required');
select is(public.get_account_deletion_request(),null::jsonb,'initially no request');
select is(public.request_account_deletion(true)->>'status','requested','request saved');
select is(public.request_account_deletion(true)->>'id',public.get_account_deletion_request()->>'id','retry returns the same request');
select is((public.get_account_deletion_request()->>'dueAt')::timestamptz-(public.get_account_deletion_request()->>'requestedAt')::timestamptz,interval '7 days','seven day deadline');
select throws_ok('select public.platform_account_deletion_requests()','42501','forbidden','ordinary user cannot inspect platform queue');
select set_config('request.jwt.claims','{"sub":"e1630000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(public.get_account_deletion_request(),null::jsonb,'another user cannot read request');
reset role;
select is((select count(*) from private.account_deletion_requests where user_id='e1630000-0000-4000-8000-000000000001'),1::bigint,'idempotence stores one request');
insert into public.platform_administrators(user_id,granted_by_user_id) values ('e1630000-0000-4000-8000-000000000002','e1630000-0000-4000-8000-000000000002');
set local role authenticated;
select throws_ok(format('select public.platform_update_account_deletion(%L,true,true)',(select r->>'id' from jsonb_array_elements(public.platform_account_deletion_requests()) r where r->>'contact_email'='deletion-163@example.invalid')),'22023','verify_account_removal_and_completion_notice_first','cannot mark an existing account as deleted');
reset role;
delete from auth.users where id='e1630000-0000-4000-8000-000000000001';
set local role authenticated;
select lives_ok(format('select public.platform_update_account_deletion(%L,true,true)',(select r->>'id' from jsonb_array_elements(public.platform_account_deletion_requests()) r where r->>'contact_email'='deletion-163@example.invalid')),'platform can record verified completion after auth removal');
reset role;
select is((select count(*) from private.account_deletion_requests where status='completed' and contact_email is null and organization_snapshot='[]'::jsonb),1::bigint,'completion clears request contact and organization snapshot');
select * from finish();
rollback;
