-- Restrict full registration PII to organization administrators and a root
-- director assignment for the exact tryout. Resource-scoped staff receive no
-- direct table access; later features use intentionally minimal projections.
create function public.can_read_full_registration_pii(target_organization_id uuid, target_tryout_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.is_active_organization_member(target_organization_id, array['owner','administrator'])
    or exists (
      select 1 from public.tryout_staff_assignments assignment
      where assignment.organization_id=target_organization_id and assignment.user_id=auth.uid()
        and assignment.role='director' and assignment.scope_kind='tryout' and assignment.tryout_id=target_tryout_id
        and assignment.revoked_at is null and (assignment.expires_at is null or assignment.expires_at>clock_timestamp())
        and public.is_active_organization_member(target_organization_id)
    );
$$;
create function public.can_read_full_athlete_pii(target_organization_id uuid, target_athlete_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.is_active_organization_member(target_organization_id, array['owner','administrator'])
    or exists (select 1 from public.tryout_registrations registration where registration.organization_id=target_organization_id and registration.athlete_id=target_athlete_id and public.can_read_full_registration_pii(target_organization_id, registration.tryout_id));
$$;

drop policy athletes_select_authorized on public.athletes;
drop policy guardians_select_administrators on public.guardians;
drop policy athlete_guardians_select_administrators on public.athlete_guardians;
drop policy registrations_select_authorized on public.tryout_registrations;
drop policy session_enrollments_select_authorized on public.session_enrollments;
drop policy duplicate_candidates_select_administrators on public.registration_duplicate_candidates;
create policy athletes_select_pii_owner_admin_or_root_director on public.athletes for select to authenticated using (public.can_read_full_athlete_pii(organization_id,id));
create policy guardians_select_pii_owner_admin_or_root_director on public.guardians for select to authenticated using (public.is_active_organization_member(organization_id,array['owner','administrator']) or exists (select 1 from public.athlete_guardians link where link.organization_id=guardians.organization_id and link.guardian_id=guardians.id and public.can_read_full_athlete_pii(link.organization_id,link.athlete_id)));
create policy athlete_guardians_select_pii_owner_admin_or_root_director on public.athlete_guardians for select to authenticated using (public.can_read_full_athlete_pii(organization_id,athlete_id));
create policy registrations_select_pii_owner_admin_or_root_director on public.tryout_registrations for select to authenticated using (public.can_read_full_registration_pii(organization_id,tryout_id));
create policy enrollments_select_pii_owner_admin_or_root_director on public.session_enrollments for select to authenticated using (public.can_read_full_registration_pii(organization_id,tryout_id));
create policy duplicate_candidates_select_pii_owner_admin_or_root_director on public.registration_duplicate_candidates for select to authenticated using (exists (select 1 from public.tryout_registrations registration where registration.organization_id=registration_duplicate_candidates.organization_id and registration.id=registration_duplicate_candidates.registration_id and public.can_read_full_registration_pii(registration.organization_id,registration.tryout_id)));

alter table public.tryout_registrations add column submission_digest text not null default repeat('0',64), add constraint tryout_registrations_organization_tryout_id_key unique (organization_id,tryout_id,id), add constraint tryout_registrations_submission_digest_check check (submission_digest ~ '^[0-9a-f]{64}$');
alter table public.session_enrollments drop constraint session_enrollments_registration_fkey;
alter table public.session_enrollments add constraint session_enrollments_registration_tryout_fkey foreign key (organization_id,tryout_id,registration_id) references public.tryout_registrations(organization_id,tryout_id,id) on delete cascade;
alter table public.registration_confirmation_tokens add column revoked_at timestamptz;

create or replace function public.submit_public_registration(p_tryout_slug text,p_submission jsonb,p_idempotency_key text,p_rate_key_hash text)
returns table(outcome text,registration_id uuid,confirmation_token text)
language plpgsql security definer set search_path='' as $$
declare target public.tryouts%rowtype; version public.registration_form_versions%rowtype; selected_division uuid; athlete uuid; guardian uuid; registration uuid; raw_token text; field jsonb; answer jsonb; v_given_name text; v_family_name text; v_guardian_name text; v_guardian_email text; v_guardian_phone text; v_birth_date date; valid_key text; payload_digest text; attempts_after integer;
begin
  if p_tryout_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' or p_idempotency_key !~ '^[A-Za-z0-9_-]{24,200}$' or p_rate_key_hash !~ '^[0-9a-f]{64}$' or jsonb_typeof(p_submission)<>'object' then raise exception 'invalid public registration request' using errcode='22023'; end if;
  if exists(select 1 from jsonb_object_keys(p_submission) key where key not in ('givenName','familyName','birthDate','guardianName','guardianEmail','guardianPhone','divisionId','responses')) then raise exception 'unknown registration field' using errcode='22023'; end if;
  select * into target from public.tryouts where slug=p_tryout_slug and status='published' and registration_starts_at<=clock_timestamp() and registration_ends_at>clock_timestamp() for update;
  if not found then return query select 'registration_closed'::text,null::uuid,null::text; return; end if;
  perform pg_advisory_xact_lock(hashtextextended(target.id::text||':'||p_idempotency_key,0));
  valid_key:=encode(extensions.digest(p_idempotency_key,'sha256'),'hex'); payload_digest:=encode(extensions.digest(p_submission::text,'sha256'),'hex');
  select id into registration from public.tryout_registrations where organization_id=target.organization_id and tryout_id=target.id and submission_key_digest=valid_key and submission_digest=payload_digest;
  if found then return query select 'replayed'::text,registration,null::text; return; end if;
  if exists(select 1 from public.tryout_registrations where organization_id=target.organization_id and tryout_id=target.id and submission_key_digest=valid_key) then return query select 'idempotency_conflict'::text,null::uuid,null::text; return; end if;
  with expired as (select key_hash from public.registration_rate_counters where expires_at<=clock_timestamp() order by expires_at limit 100) delete from public.registration_rate_counters where key_hash in (select key_hash from expired);
  insert into public.registration_rate_counters(key_hash,attempts,window_started_at,expires_at) values(p_rate_key_hash,1,clock_timestamp(),clock_timestamp()+interval '10 minutes') on conflict(key_hash) do update set attempts=case when public.registration_rate_counters.expires_at<=clock_timestamp() then 1 else public.registration_rate_counters.attempts+1 end,window_started_at=case when public.registration_rate_counters.expires_at<=clock_timestamp() then clock_timestamp() else public.registration_rate_counters.window_started_at end,expires_at=case when public.registration_rate_counters.expires_at<=clock_timestamp() then clock_timestamp()+interval '10 minutes' else public.registration_rate_counters.expires_at end returning attempts into attempts_after;
  if attempts_after>10 then return query select 'rate_limited'::text,null::uuid,null::text; return; end if;
  select v.* into version from public.tryout_registration_form_selections s join public.registration_form_versions v on v.organization_id=s.organization_id and v.tryout_id=s.tryout_id and v.id=s.registration_form_version_id where s.organization_id=target.organization_id and s.tryout_id=target.id and v.status='published' for update of s,v;
  if not found then return query select 'registration_closed'::text,null::uuid,null::text; return; end if;
  v_given_name:=trim(coalesce(p_submission->>'givenName','')); v_family_name:=trim(coalesce(p_submission->>'familyName','')); v_guardian_name:=trim(coalesce(p_submission->>'guardianName','')); v_guardian_email:=public.normalize_registration_text(coalesce(p_submission->>'guardianEmail','')); v_guardian_phone:=trim(coalesce(p_submission->>'guardianPhone',''));
  begin v_birth_date:=(p_submission->>'birthDate')::date; exception when others then raise exception 'invalid birth date' using errcode='22023'; end;
  if char_length(v_given_name) not between 1 and 120 or char_length(v_family_name) not between 1 and 120 or char_length(v_guardian_name) not between 1 and 160 or v_guardian_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' or (v_guardian_phone<>'' and v_guardian_phone !~ '^[+]?[0-9 ()-]{7,32}$') or v_birth_date>current_date then raise exception 'invalid identity' using errcode='22023'; end if;
  if jsonb_typeof(p_submission->'responses')<>'object' or octet_length((p_submission->'responses')::text)>16384 then raise exception 'invalid responses' using errcode='22023'; end if;
  if exists(select 1 from jsonb_object_keys(p_submission->'responses') k where not exists(select 1 from jsonb_array_elements(version.schema->'fields') f where f->>'key'=k)) then raise exception 'unknown registration response' using errcode='22023'; end if;
  for field in select value from jsonb_array_elements(version.schema->'fields') loop answer:=p_submission->'responses'->(field->>'key'); if (field->>'required')::boolean and (answer is null or answer='null'::jsonb or answer='""'::jsonb) then raise exception 'required response missing' using errcode='22023'; end if; if answer is null or answer='null'::jsonb then continue; end if; if field->>'kind' in ('consent','checkbox') and jsonb_typeof(answer)<>'boolean' then raise exception 'invalid response' using errcode='22023'; end if; if field->>'kind'='consent' and (field->>'required')::boolean and answer<>'true'::jsonb then raise exception 'required consent missing' using errcode='22023'; end if; if field->>'kind'='select' and (jsonb_typeof(answer)<>'string' or not((field->'options') ? (answer#>>'{}'))) then raise exception 'invalid response' using errcode='22023'; end if; if field->>'kind' in ('text','email','phone','date','textarea') and (jsonb_typeof(answer)<>'string' or octet_length(answer#>>'{}')>case when field->>'kind'='textarea' then 5000 else 500 end) then raise exception 'invalid response' using errcode='22023'; end if; end loop;
  selected_division:=nullif(p_submission->>'divisionId','')::uuid; if selected_division is null then select id into selected_division from public.tryout_divisions where organization_id=target.organization_id and tryout_id=target.id order by sort_order limit 1; end if; if not exists(select 1 from public.tryout_divisions where organization_id=target.organization_id and tryout_id=target.id and id=selected_division) then raise exception 'invalid division' using errcode='22023'; end if;
  insert into public.athletes(organization_id,given_name,family_name,normalized_given_name,normalized_family_name,birth_date) values(target.organization_id,v_given_name,v_family_name,public.normalize_registration_text(v_given_name),public.normalize_registration_text(v_family_name),v_birth_date) returning id into athlete; insert into public.guardians(organization_id,name,email,normalized_email) values(target.organization_id,v_guardian_name,v_guardian_email,v_guardian_email) returning id into guardian; insert into public.athlete_guardians(organization_id,athlete_id,guardian_id) values(target.organization_id,athlete,guardian); insert into public.tryout_registrations(organization_id,tryout_id,athlete_id,division_id,registration_form_version_id,responses,submission_key_digest,submission_digest) values(target.organization_id,target.id,athlete,selected_division,version.id,p_submission->'responses',valid_key,payload_digest) returning id into registration; insert into public.session_enrollments(organization_id,tryout_id,registration_id,session_id) select target.organization_id,target.id,registration,s.id from public.tryout_sessions s where s.organization_id=target.organization_id and s.tryout_id=target.id and s.division_id=selected_division; insert into public.registration_duplicate_candidates(organization_id,registration_id,candidate_athlete_id,reason) select target.organization_id,registration,c.id,'name_birthdate_guardian_email' from public.athletes c join public.athlete_guardians l on l.organization_id=c.organization_id and l.athlete_id=c.id join public.guardians g on g.organization_id=l.organization_id and g.id=l.guardian_id where c.organization_id=target.organization_id and c.id<>athlete and c.normalized_given_name=public.normalize_registration_text(v_given_name) and c.normalized_family_name=public.normalize_registration_text(v_family_name) and c.birth_date=v_birth_date and g.normalized_email=v_guardian_email;
  raw_token:=encode(extensions.gen_random_bytes(32),'hex'); update public.registration_confirmation_tokens set revoked_at=clock_timestamp() where public.registration_confirmation_tokens.organization_id=target.organization_id and public.registration_confirmation_tokens.registration_id=registration and purpose='registration_confirmation' and used_at is null and revoked_at is null; insert into public.registration_confirmation_tokens(organization_id,registration_id,token_digest,expires_at) values(target.organization_id,registration,encode(extensions.digest(raw_token,'sha256'),'hex'),clock_timestamp()+interval '7 days'); return query select 'submitted'::text,registration,raw_token;
end; $$;

create function public.consume_registration_confirmation_token(p_token text) returns table(outcome text,registration_id uuid) language plpgsql security definer set search_path='' as $$ declare v_digest text; begin if p_token !~ '^[0-9a-f]{64}$' then return query select 'not_found'::text,null::uuid; return; end if; v_digest:=encode(extensions.digest(p_token,'sha256'),'hex'); update public.registration_confirmation_tokens set used_at=clock_timestamp() where registration_confirmation_tokens.token_digest=v_digest and purpose='registration_confirmation' and used_at is null and revoked_at is null and expires_at>clock_timestamp() returning registration_confirmation_tokens.registration_id into registration_id; if found then return query select 'consumed'::text,registration_id; else return query select 'not_found'::text,null::uuid; end if; end; $$;

create function public.prevent_reserved_registration_form_fields() returns trigger language plpgsql set search_path='' as $$ declare field jsonb; begin for field in select value from jsonb_array_elements(new.schema->'fields') loop if field->>'key' in ('given_name','family_name','birth_date','guardian_name','guardian_email','guardian_phone','guardian','division_id','responses','idempotency_key') then raise exception 'reserved registration form field' using errcode='23514'; end if; end loop; return new; end; $$;
create trigger prevent_reserved_registration_form_fields before insert or update of schema on public.registration_form_versions for each row execute function public.prevent_reserved_registration_form_fields();
revoke all on function public.can_read_full_registration_pii(uuid,uuid),public.can_read_full_athlete_pii(uuid,uuid),public.consume_registration_confirmation_token(text) from public;
grant execute on function public.consume_registration_confirmation_token(text) to service_role;
