create function public.participant_schedule() returns jsonb language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_agg(jsonb_build_object('organization_id',l.organization_id,'athlete_id',l.athlete_id,'event',t.name,'session',s.name,'starts_at',s.starts_at,'ends_at',s.ends_at,'timezone',t.timezone,'group',g.name,'checked_in',exists(select 1 from public.checkins c where c.organization_id=l.organization_id and c.registration_id=r.id and c.session_id=s.id and c.reversed_at is null)) order by s.starts_at),'[]') from public.participant_links l join public.tryout_registrations r on r.organization_id=l.organization_id and r.athlete_id=l.athlete_id join public.tryouts t on t.organization_id=r.organization_id and t.id=r.tryout_id join public.session_enrollments e on e.organization_id=r.organization_id and e.registration_id=r.id join public.tryout_sessions s on s.organization_id=e.organization_id and s.id=e.session_id left join public.session_groups g on g.organization_id=e.organization_id and g.id=e.group_id where l.user_id=auth.uid() and l.active;
$$;
create function public.participant_registration_options() returns jsonb language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_agg(jsonb_build_object('organization_id',l.organization_id,'athlete_id',l.athlete_id,'name',t.name,'slug',t.slug) order by t.name),'[]') from public.participant_links l join public.tryouts t on t.organization_id=l.organization_id and t.status='published' where l.user_id=auth.uid() and l.active;
$$;
create function public.participant_registration_prefill(p_tryout_slug text,p_athlete_id uuid) returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('givenName',a.given_name,'familyName',a.family_name,'birthDate',coalesce(a.birth_date::text,'')) from public.athletes a join public.tryouts t on t.organization_id=a.organization_id where t.slug=p_tryout_slug and t.status='published' and a.id=p_athlete_id and public.can_view_participant(a.organization_id,a.id);
$$;
revoke all on function public.participant_schedule(),public.participant_registration_options(),public.participant_registration_prefill(text,uuid) from public,anon,service_role;
grant execute on function public.participant_schedule(),public.participant_registration_options(),public.participant_registration_prefill(text,uuid) to authenticated;
