import type { GuideChapter, GuideStep } from './guide-content';
const step = (
  id: string,
  title: string,
  image: string,
  where: string,
  actions: string[],
  result: string,
  note?: string,
): GuideStep => ({ id: `checkin-${id}`, title, image, where, actions, result, note });
export const checkinGuide: GuideChapter[] = [
  {
    id: 'checkin-access',
    title: 'Join the event team',
    description:
      'Get the right account, assignment and event-day instructions before arrivals begin.',
    steps: [
      step(
        'invitation',
        'Accept the organizer’s invitation',
        'evaluator-invitation',
        'Invitation link → Sign in → Accept invitation',
        [
          'Open the invitation sent by the organizer and sign in with the invited email address. If you need an account, register and verify that email, then return to the invitation.',
          'Check the organization and choose Accept invitation. Keep your invitation link private.',
          'Ask the organizer to assign check-in access to the event, division, session or group you will cover. Membership alone does not grant check-in access.',
          'Ask for a replacement if the invitation has expired; do not create a separate organization.',
        ],
        'Your account belongs to the event’s organization and can receive a check-in assignment.',
        'Staff share the same invitation screen. The example shows it after sign-in.',
      ),
      step(
        'sign-in',
        'Sign in and check your assigned workspace',
        'checkin-workspace',
        'Sign in → My workspace',
        [
          'Sign in using your own invited account. Use Forgot your password? or the verification-link help on Sign in if needed.',
          'Check the organization name and look for Check-in under My workspace. On a phone, open the navigation menu.',
          'If several event links are shown, open the one your organizer assigned and verify the event heading.',
          'If the expected link is missing, confirm your account email and ask the organizer to check your active assignment.',
        ],
        'You have reached your authorized event-day workspace.',
      ),
      step(
        'prepare',
        'Prepare your desk and escalation contact',
        'checkin-placement',
        'Check-in → Event heading and session controls',
        [
          'Confirm the event, arrival times, session or group allocation and number-assignment policy with the organizer.',
          'Have the required bibs or numbers and a charged device ready. Check that the venue connection works before the arrival rush.',
          'Know who handles registration corrections, absences, capacity problems and eligibility questions.',
          'Use the Check-in page for arrivals. Other journey links may require additional permissions.',
        ],
        'You know the check-in procedure and who can resolve an exception.',
      ),
    ],
  },
  {
    id: 'checkin-identification',
    title: 'Find the correct registration',
    description: 'Choose the placement first, then match the athlete before recording an arrival.',
    steps: [
      step(
        'session',
        'Select the session and group',
        'checkin-placement',
        'Check-in → Session and group',
        [
          'Select the athlete’s intended Session and group before searching.',
          'Match it to the event schedule and the organizer’s instructions; similar session names can belong to different days.',
          'When you change placement, search again and recheck the returned record. Numbers and attendance apply within the selected scope.',
          'If the expected placement is absent, ask the organizer to check your access and the session setup.',
        ],
        'Your search and check-in will apply to the intended placement.',
      ),
      step(
        'search',
        'Search by athlete or registration reference',
        'checkin-search',
        'Check-in → Search registrations',
        [
          'Enter at least two characters of the athlete or guardian name, or an available registration reference. The field also accepts permitted phone, QR and tryout-number lookups.',
          'Choose Search and wait for the result count.',
          'Match the athlete name, division and registration reference with the person at the desk. Ask for another identifying detail when names are similar.',
          'Choose the correct registration only after resolving any identity mismatch.',
        ],
        'You have identified the correct registration in the selected session.',
      ),
      step(
        'qr',
        'Use a family’s QR or confirmation reference',
        'checkin-search',
        'Family confirmation → Check-in search',
        [
          'Ask the family to show their registration confirmation when name matching is unclear.',
          'Use the QR reference or registration ID in Search registrations. If a QR link opens check-in with a prefilled reference, verify the event and selected placement.',
          'Run the search and compare the returned athlete and division with the family’s confirmation.',
          'Do not treat the presence of a QR code as proof of check-in. A successful check-in receipt is still required.',
        ],
        'The confirmation helps identify the registration before arrival is recorded.',
        'The screenshot shows the same search field with a name lookup. This page does not provide an in-page camera scanner.',
      ),
      step(
        'missing',
        'Resolve missing or unsuitable registrations',
        'checkin-empty',
        'Check-in → Search result or warning',
        [
          'For No matching registrations, check spelling, event and placement, then try the registration reference.',
          'If the result is withdrawn, cancelled or missing information, ask the organizer to review the underlying registration.',
          'Do not create a duplicate athlete or select a similarly named person to get past a problem.',
          'Keep the arrival waiting for staff assistance until identity and eligibility to check in are resolved.',
        ],
        'The organizer can correct the source record without attendance being attached to the wrong athlete.',
        'This image shows the no-match state; other exceptions display their own warning.',
      ),
    ],
  },
  {
    id: 'checkin-arrival',
    title: 'Assign a number and confirm arrival',
    description: 'A requested number is provisional until the server confirms the check-in.',
    steps: [
      step(
        'number',
        'Choose automatic or requested numbering',
        'checkin-number-result',
        'Check-in → Requested number (optional)',
        [
          'Follow the organizer’s number policy. Leave Requested number blank for automatic assignment, or enter the specific number you are issuing.',
          'A requested number must be a whole number from 1 to 9999 and available in this placement’s numbering scope.',
          'Check the field again for each athlete; a value from the previous check-in can remain in the form.',
          'Do not hand over a requested bib until the returned receipt confirms the actual assigned number.',
        ],
        'You have selected the numbering method and know to verify the returned number.',
        'The example shows a successful requested-number receipt. The number displayed in an initial search can differ from the newly confirmed placement number.',
      ),
      step(
        'submit',
        'Record and verify the check-in',
        'checkin-confirmed',
        'Registration result → Check in [athlete]',
        [
          'Recheck the athlete, session/group and requested number, then choose Check in for that athlete.',
          'Wait for the message naming the athlete as checked in and showing the assigned number.',
          'Confirm the result card changes to checked in and agrees with the receipt. Issue that number and explain where the athlete should go next.',
          'If you receive a warning instead, resolve it before treating the arrival as recorded.',
        ],
        'The server has confirmed attendance and the assigned number.',
      ),
      step(
        'conflict',
        'Recover from a duplicate number',
        'checkin-conflict',
        'Check-in → That number is already active',
        [
          'Read the duplicate-number warning and its suggested available number.',
          'Replace Requested number with the suggested number, or clear it for automatic numbering if your organizer allows it.',
          'Check in the same athlete again and wait for a successful receipt.',
          'Use the number from the successful receipt, since another desk may have used the suggestion in the meantime.',
        ],
        'The athlete receives an available number without replacing someone else’s assignment.',
        'The local example rejected number 12, suggested 1, and then successfully confirmed number 1.',
      ),
      step(
        'repeat',
        'Recognize an athlete who is already checked in',
        'checkin-repeat',
        'Checked-in result → Confirm [athlete] again',
        [
          'Read the existing checked-in status and number before taking another action.',
          'If confirmation is needed, choose Confirm [athlete] again and look for was already checked in.',
          'Use the existing confirmed number. Repeat confirmation is not a way to transfer sessions or renumber someone.',
          'Ask the organizer to handle a correction rather than repeatedly submitting different identities or placements.',
        ],
        'You confirm the existing arrival without creating a second one.',
      ),
      step(
        'connection',
        'Handle unconfirmed check-ins and other warnings',
        'checkin-conflict',
        'Check-in → Status message',
        [
          'Read the exact message. A full session, unavailable placement, access restriction and a connection failure require different responses.',
          'If the outcome could not be confirmed and the app says it is safe to retry, restore the connection and retry the same athlete and placement.',
          'Wait for checked in or already checked in before issuing the final number. Do not assume a failed request is queued for offline completion.',
          'Escalate persistent failures, capacity limits or permission changes to the organizer.',
        ],
        'Each arrival has a confirmed outcome or a clearly identified exception.',
        'The screenshot illustrates the status-message location with a number conflict; it is not an offline receipt.',
      ),
    ],
  },
  {
    id: 'checkin-close',
    title: 'Continue and hand over',
    description: 'Keep the queue accurate and leave a clear record for the next staff member.',
    steps: [
      step(
        'next',
        'Reset the details for the next arrival',
        'checkin-confirmed',
        'Check-in → Search registrations',
        [
          'After confirming arrival, explain the athlete’s next location and group instructions.',
          'Replace the search with the next athlete. Recheck Session and group and clear or change Requested number.',
          'Repeat identity matching, submission and receipt verification for every athlete.',
          'Tell the organizer about unresolved registrations or expected athletes who have not arrived.',
        ],
        'Each check-in is deliberate and uses the correct details.',
      ),
      step(
        'handoff',
        'Finish your shift and sign out',
        'evaluator-sign-out',
        'Event desk handoff → Sign out',
        [
          'Finish any pending check-in and confirm its outcome before leaving the device.',
          'Give the organizer or incoming staff member the unresolved issues, affected sessions and number discrepancies through the agreed channel.',
          'Have the next staff member use their own account. Choose Sign out and verify that the sign-in screen appears.',
          'Keep registration details and any printed attendance material with authorized event staff.',
        ],
        'Your shift is handed over and your account is signed out.',
      ),
    ],
  },
];
