import type { GuideChapter, GuideStep } from './guide-content';

const step = (
  id: string,
  title: string,
  image: string,
  where: string,
  actions: string[],
  result: string,
  note?: string,
): GuideStep => ({ id, title, image, where, actions, result, note });

export const evaluatorGuide: GuideChapter[] = [
  {
    id: 'evaluator-access',
    title: 'Accept your invitation & sign in',
    description: 'Join the organizer’s existing workspace using your own invited account.',
    steps: [
      step(
        'evaluator-invitation',
        'Open and accept your invitation',
        'evaluator-invitation',
        'Organizer’s invitation link → Your invitation is ready',
        [
          'Open the invitation link shared with you by the organizer. Keep it private and use the email address that received the invitation.',
          'If asked, choose Continue to sign in. If you need an account, register using the invited email and verify it, then return to the invitation link.',
          'When signed in with the correct account, choose Accept invitation to join the existing organization.',
          'If the invitation is invalid or expired, ask the organizer for a replacement. Do not create a separate club to work around an invitation problem.',
        ],
        'You join the organizer’s workspace. Scoring access still depends on an active evaluator assignment.',
        'The screenshot shows the acceptance screen after sign-in. It does not show a private invitation link.',
      ),
      step(
        'evaluator-sign-in',
        'Sign in with your evaluator account',
        'evaluator-sign-in',
        'Sign in',
        [
          'Enter the invited email and your password. Complete the displayed bot-protection check when required.',
          'Choose Sign in and check which organization you have entered.',
          'Use Need a new verification link? if your email is not yet verified, or Forgot your password? if you cannot sign in.',
          'Use your own account on every device. Do not share an organizer’s or another evaluator’s login.',
        ],
        'Your account is authenticated and the permitted workspace opens.',
      ),
      step(
        'evaluator-find-workspace',
        'Find your assigned evaluation work',
        'evaluator-sessions',
        'Workspace navigation → Evaluate',
        [
          'Choose Evaluate in the workspace navigation. On a phone, open the navigation menu first.',
          'Review Your assigned sessions and check the event name attached to each session.',
          'If a session is missing or unavailable, confirm the organization and account email, then ask the organizer to check your assignment.',
          'An organization invitation alone does not assign athletes to you. The organizer controls your tryout, division, session or group scope.',
        ],
        'You know which sessions you are authorized to evaluate.',
      ),
    ],
  },
  {
    id: 'evaluator-prepare',
    title: 'Prepare before the first athlete',
    description: 'Give the organizer your context and agree on what each score means.',
    steps: [
      step(
        'evaluator-profile',
        'Complete your evaluator profile',
        'coach-evaluator-profile',
        'Evaluate → View evaluator profile',
        [
          'Enter your display name, affiliation, sport and position or skill specialties.',
          'Add relevant qualifications, coaching or scouting experience and availability.',
          'Record conflicts of interest or situations where you should step aside from evaluating an athlete. Discuss them with the organizer.',
          'Choose Save profile and check the result. Update your profile when your availability or circumstances change.',
        ],
        'Organization managers can review your experience, availability and declared conflicts.',
      ),
      step(
        'evaluator-readiness',
        'Review the rubric and confirm your preparation',
        'evaluator-readiness',
        'Evaluator profile → Preparation declarations',
        [
          'Review the scoring rubric with the organizer: category definitions, scales, weights and examples of strong or weak performance.',
          'Check your current assignments and confirm you can cover the scheduled sessions.',
          'Test scoring and synchronization on the device you will use, using an organizer-approved practice workflow.',
          'Check each preparation declaration only after doing that work, then save your profile. Reconfirm with the organizer when assignments change.',
        ],
        'Your preparation is recorded and you understand the event’s scoring expectations.',
        'These declarations are self-reported. Checking a box does not test a device or complete a briefing for you.',
      ),
      step(
        'evaluator-calibration',
        'Complete calibration if the organizer provides it',
        'evaluator-calibration',
        'Evaluator profile → Evaluator calibration',
        [
          'Open Evaluator calibration to look for shared practice observations.',
          'If a case is available, read its instructions and submit your own assessment before reviewing the reference answer.',
          'Discuss differences with the organizer so the team interprets the rubric consistently.',
          'If no cases are available, follow the organizer’s briefing and practice instructions instead.',
        ],
        'You have a shared understanding of how to apply the rubric.',
        'The example workspace has no calibration cases. Calibration discussions do not automatically change athlete scores or evaluator weights.',
      ),
    ],
  },
  {
    id: 'evaluator-score',
    title: 'Open the right athlete & score independently',
    description: 'Check identity and session first, then record your own observations.',
    steps: [
      step(
        'evaluator-open-session',
        'Open the correct scoring session',
        'evaluator-session',
        'Evaluate → Open scoring session',
        [
          'Find the correct event and select Open scoring session beside the session you will evaluate.',
          'Check the session name and your completed count before continuing.',
          'Choose Assigned athletes to review the list, or Continue scoring to return to the next available scorecard.',
        ],
        'You are working within the intended session and assignment.',
      ),
      step(
        'evaluator-identify-athlete',
        'Match the athlete to the scorecard',
        'evaluator-athletes',
        'Scoring session → Assigned athletes',
        [
          'Match the displayed tryout number, athlete identity, division and session or group to the person you are observing.',
          'Choose Start evaluation or Open evaluation for that athlete.',
          'Check the identity again at the top of the scorecard. If the event uses blind identity, use the supplied number and session information.',
          'If the person or number does not match, stop and ask event staff to correct the record before entering scores.',
        ],
        'Your evaluation will be recorded against the correct athlete and session.',
      ),
      step(
        'evaluator-enter-scores',
        'Enter a score for each required category',
        'coach-score-athlete',
        'Athlete scorecard → Scores',
        [
          'Read each category and its scoring scale. Select one whole-number score using the rubric guidance.',
          'Work through every required category; the scoring progress indicator shows how many you have scored.',
          'Use the displayed 1–5 or 1–10 scale correctly. Do not substitute your own scale or change a score to match another evaluator.',
          'If you have not seen enough evidence to score a category, ask for another observation or guidance instead of inventing a result.',
        ],
        'The scorecard contains your independent category scores.',
      ),
      step(
        'evaluator-notes',
        'Add useful private notes and flags',
        'evaluator-notes',
        'Athlete scorecard → Your private notes',
        [
          'Describe specific observed actions and situations, including strengths and what needs another look.',
          'Use the available flags when relevant, such as Needs another look, Injury concern or Eligibility review.',
          'Keep comments factual and relevant to the tryout. Raise urgent event-day concerns directly with staff as well.',
          'Check the note belongs to this athlete before moving on. Other evaluators cannot see your private note during live evaluation.',
        ],
        'Your scores have useful supporting observations and appropriate follow-up flags.',
      ),
      step(
        'evaluator-my-profile',
        'Review your own Athlete Profile',
        'coach-complete-evaluation',
        'Athlete scorecard → Athlete Profile → My Evaluation',
        [
          'Choose My Evaluation to inspect your own score breakdown.',
          'Review the weighted total after the required criteria are scored. It uses this scorecard’s rubric weights.',
          'Use the criterion table to check the actual scores. A radar chart requires at least three scored criteria.',
          'Correct an accidental entry while the scorecard is editable, then recheck its save status.',
        ],
        'You can verify the score breakdown without confusing the total with a team-selection decision.',
        'The example screenshot is a completed two-category scorecard, so it shows a table and read-only controls.',
      ),
      step(
        'evaluator-average',
        'Understand the evaluator average',
        'coach-average',
        'Athlete Profile → Evaluator Average',
        [
          'Choose Evaluator Average when the aggregate is available to your assignment.',
          'Check the number of completed evaluations and the session and rubric context.',
          'Treat missing evidence or a small number of evaluations as context for the average. Continue applying the rubric independently.',
          'Return to My Evaluation to review your own scorecard. The aggregate does not disclose other evaluators’ private notes.',
        ],
        'You can distinguish your individual evaluation from the authorized aggregate.',
      ),
    ],
  },
  {
    id: 'evaluator-save',
    title: 'Confirm saves & complete evaluations',
    description: 'Keep device drafts, server saves and completed evaluations clearly separate.',
    steps: [
      step(
        'evaluator-save-status',
        'Wait for server confirmation',
        'evaluator-saved',
        'Athlete scorecard → Save status',
        [
          'After editing, watch the save status instead of assuming the score is already stored on the server.',
          'Wait for Saved on server. Use Save now only when it is enabled and a save is needed.',
          'If the state is still editing, saving, queued or saved on device, keep the session available and wait for the result.',
          'Resolve any warning before treating the evaluation as finished.',
        ],
        'The app confirms that the server has received the current draft.',
      ),
      step(
        'evaluator-offline',
        'Handle a lost connection without losing your work',
        'evaluator-offline',
        'Athlete scorecard → Offline or Saved on device',
        [
          'Read the exact status. Saved on device means the draft is retained on that device and still needs server confirmation.',
          'Keep using the same browser and device while restoring connectivity. Do not clear site data or assume another device has the draft.',
          'If the message says the copy is only retained for the browser session, keep that session open until the work is safe.',
          'Reconnect, allow synchronization to run and wait for Saved on server. Complete the evaluation only after the required scores and save state allow it.',
        ],
        'The local work reaches the server, or you have a clear warning to resolve.',
        'This screenshot was captured during an actual simulated connection loss in the local demo. Completion stays disabled while the draft is unconfirmed.',
      ),
      step(
        'evaluator-recovery',
        'Pause and resolve save or access warnings',
        'evaluator-offline',
        'Athlete scorecard → Save or recovery warning',
        [
          'If a save is unconfirmed, a conflict appears or access changes, read the message before reloading or retrying.',
          'Preserve unsynced work. Use copy or download controls when offered, and follow the screen’s instructions about whether reloading is safe.',
          'For conflicting versions, compare the available local and server information. Do not replace a draft unless you understand which work will be discarded.',
          'Ask the organizer for help with locked scorecards, revoked assignments or an unclear recovery decision. Share only the information needed through the agreed support channel.',
        ],
        'You preserve your observations and resolve the warning before continuing.',
        'The image shows a queued device draft. Conflict and access warnings have different wording and controls; follow the warning actually shown on your device.',
      ),
      step(
        'evaluator-complete',
        'Explicitly complete the evaluation',
        'evaluator-completed',
        'Athlete scorecard → Complete evaluation',
        [
          'Review the athlete identity, required category scores, notes and flags one last time.',
          'Wait for server confirmation, then choose Complete evaluation when the button is enabled.',
          'Check for Evaluation complete and the Evaluation completed button state.',
          'If you need a correction after completion, contact the organizer about the appropriate reopening process rather than creating a second scorecard.',
        ],
        'The completed evaluation contributes to the permitted progress counts and score evidence.',
        'Saving a draft and completing an evaluation are separate actions.',
      ),
    ],
  },
  {
    id: 'evaluator-finish',
    title: 'Finish the session & hand off',
    description: 'Check all remaining work before leaving the venue or signing out.',
    steps: [
      step(
        'evaluator-next-athlete',
        'Continue to the next assigned athlete',
        'evaluator-completed',
        'Scorecard → Previous athlete / Next athlete',
        [
          'After confirming completion, use Next athlete or return to Assigned athletes to choose the next person.',
          'Recheck the name or blind identifier, tryout number and session on every scorecard.',
          'Repeat scoring, save verification and explicit completion for each assigned athlete you observe.',
          'Tell the organizer about an absent athlete or someone you could not evaluate; do not fill gaps with guessed scores.',
        ],
        'You continue through the correct assignment without carrying observations onto the wrong athlete.',
      ),
      step(
        'evaluator-progress',
        'Check your remaining evaluations',
        'evaluator-progress',
        'Scoring session → Your progress',
        [
          'Return to the session and open Your progress.',
          'Review Complete, In progress and Assigned together. A saved draft is still in progress until completed.',
          'Use View assigned athletes to identify work that is unfinished or not started.',
          'Return to each applicable scorecard to finish it, or agree with the organizer how absences and assignment changes should be handled.',
        ],
        'You know exactly how much of your assigned work is complete.',
        'The example intentionally shows an unfinished session. This view reports your own evaluation states, not the whole event’s completion.',
      ),
      step(
        'evaluator-handoff',
        'Confirm the handoff with the organizer',
        'evaluator-progress',
        'Your progress → Organizer follow-up',
        [
          'Check every session you were assigned, not only the last one you opened.',
          'Confirm that completed work is saved on the server and explain any remaining drafts, missing observations or unresolved warnings.',
          'Tell the organizer about athletes who need another look and any declared conflicts that affected coverage.',
          'Leave roster selection, final approval and family communication to the people responsible for those tasks.',
        ],
        'The organizer knows which observations are complete and what still needs attention.',
      ),
      step(
        'evaluator-sign-out',
        'Sign out after your work is confirmed',
        'evaluator-sign-out',
        'Workspace navigation → Sign out',
        [
          'Before leaving, confirm that no device-only drafts or unresolved save warnings remain.',
          'Choose Sign out in the workspace navigation, especially on a shared device.',
          'Check that the sign-in screen appears. If you return later, use the same evaluator account to find your assigned sessions.',
          'For later corrections, contact the organizer with the event, session and athlete reference through the agreed channel.',
        ],
        'Your session is closed and the organizer has the completed evaluation work.',
      ),
    ],
  },
];
