import { organizationTeamsGuide, singleTryoutGuide } from './plan-guides';
import { evaluatorGuide } from './evaluator-guide';
import { checkinGuide } from './checkin-guide';
import { reviewerGuide } from './reviewer-guide';
import { scoutingGuide } from './scouting-guide';

export type GuideStep = {
  id: string;
  title: string;
  image: string;
  where: string;
  actions: string[];
  result: string;
  note?: string;
};
export type GuideChapter = { id: string; title: string; description: string; steps: GuideStep[] };
export const guideAudiences = [
  'coaches',
  'evaluators',
  'parents',
  'checkin',
  'reviewers',
  'scouting',
] as const;
export type GuideAudience = (typeof guideAudiences)[number];
export function isGuideAudience(value: string | null): value is GuideAudience {
  return guideAudiences.some((audience) => audience === value);
}
const step = (
  id: string,
  title: string,
  image: string,
  where: string,
  actions: string[],
  result: string,
  note?: string,
): GuideStep => ({ id, title, image, where, actions, result, note });

export const guides: Record<GuideAudience, GuideChapter[]> = {
  evaluators: evaluatorGuide,
  checkin: checkinGuide,
  reviewers: reviewerGuide,
  scouting: scoutingGuide,
  coaches: [
    {
      id: 'coach-account',
      title: 'Set up your account & club',
      description: 'Start as the organizer, or join the organization that invited you.',
      steps: [
        step(
          'coach-create-account',
          'Create your organization account',
          'coach-sign-up',
          'Sign in → Create an organization account',
          [
            'Use your own email address and enter a password that meets the requirements shown. Enter the same password again in the confirmation field.',
            'Complete the bot-protection check when it appears, then choose Create account. Use an email inbox you can open now.',
            'If you already have an account, sign in instead. If a club invited you, open its invitation link and use the invited email rather than creating a second organization.',
          ],
          'The app asks you to verify your email before continuing.',
          'An organization account is for staff who run tryouts. Parents should use the participant-account path.',
        ),
        step(
          'coach-verify-email',
          'Verify your email and sign in',
          'verify-email',
          'Your email inbox → verification link → Sign in',
          [
            'Open the TryoutFlow verification email in the inbox you used to register. Check junk or spam if it is missing.',
            'Follow the verification link, then sign in using the same email and password.',
            'For a missing or expired email, choose Need a new verification link? on Sign in and request another. Use the newest message.',
          ],
          'You can continue to organization setup, or return to an existing workspace.',
          'The screenshot shows the in-app verification/resend screen. Your email application will look different.',
        ),
        step(
          'coach-create-organization',
          'Create your club workspace',
          'coach-organization',
          'Pricing → Try Pro free for 7 days → Set up your organization',
          [
            'Enter the organization name your coaches and families will recognize.',
            'Choose a unique TryoutFlow workspace address using the format shown. This is your internal workspace address; it does not replace your club website.',
            'Check the timezone carefully, then submit the organization setup form. Session dates and times depend on this setting.',
          ],
          'Your organization dashboard opens and you become its first owner.',
          'Invited staff join the existing organization; they do not need to create a new club.',
        ),
        step(
          'coach-orientation',
          'Find your way around the workspace',
          'coach-dashboard',
          'Home',
          [
            'Use Tryouts for event setup, Athletes for individual records, and Evaluators for your evaluation team.',
            'Use the operations checklist and the recent-tryout links to return to the next unfinished task.',
            'Open a tryout to find its Prepare, Run event, Make decisions and Communicate sections. On a phone, use the navigation menu or section selector.',
          ],
          'You know where the organization tools and individual tryout tools live.',
          'The screenshots show an owner account. Directors, evaluators and check-in staff see only the tools permitted by their assignments.',
        ),
        step(
          'coach-settings',
          'Set your defaults and organization logo',
          'coach-settings',
          'Settings',
          [
            'Review the timezone and the singular/plural words used for athletes.',
            'Choose or type the sports and quick tags you commonly use, then select Save settings.',
            'Under Organization logo, choose a square PNG, JPEG or WebP within the displayed size limit and select Upload logo. Check the saved preview.',
          ],
          'Your workspace defaults are saved and your logo appears on supported organization surfaces.',
          'Shared program defaults and custom branding require Organization access. Manage them in the parent workspace; teams inherit them and retain their own timezone.',
        ),
        step(
          'coach-invite',
          'Invite your coaches and other staff',
          'coach-members',
          'Members → Invite a member',
          [
            'Enter the staff member’s email and choose Member or Administrator. Give each person only the organization access they need.',
            'Choose Create invitation and share the generated invitation link directly with that person.',
            'Have the person open the link and accept using the invited account. Check the invitation history and membership status afterward.',
            'Assign event-specific evaluator access in the tryout’s Staff screen; organization membership alone does not assign scoring work.',
          ],
          'Your staff join the same workspace, and you can see whether invitations are still pending.',
        ),
      ],
    },
    organizationTeamsGuide,
    singleTryoutGuide,
    {
      id: 'coach-setup',
      title: 'Build & publish a tryout',
      description:
        'Complete all seven setup stages before sharing registration. These setup screenshots show a subscription event reopened after publication (Edit tryout setup / Save changes). Single Tryout instead freezes its identity, divisions and schedule at publication; follow the Single Tryout chapter for that plan.',
      steps: [
        step(
          'coach-create-tryout',
          'Create the draft event',
          'coach-create-tryout',
          'Home → Create Tryout, or Tryouts → create action',
          [
            'Enter a clear tryout name and its sport.',
            'Choose an existing cycle/season, or choose Create a new cycle and enter its name. Use one of these options.',
            'Confirm the timezone and set the registration opening and closing dates. These control registration availability, not the actual session times.',
            'Choose Create draft. You will enter the guided setup.',
          ],
          'A draft tryout exists and opens at Basics.',
        ),
        step(
          'coach-basics',
          'Check the event basics and registration window',
          'coach-basics',
          'Guided setup → Basics',
          [
            'Review the saved name, sport and timezone. Correct mistakes before continuing.',
            'Set when families may start registering and the closing deadline. The closing time must follow the opening time.',
            'Choose Save and continue. Use the setup-step links whenever you need to revisit a saved stage.',
          ],
          'Basics is marked complete and the Divisions stage opens.',
        ),
        step(
          'coach-divisions',
          'Add age groups or divisions',
          'coach-divisions',
          'Guided setup → Divisions',
          [
            'Enter the division name, such as U15, a competition level, or another grouping your club uses.',
            'Add an optional description and age limits when appropriate for the event.',
            'Use Save and add another for more divisions. When finished, use Save and continue.',
            'To change an existing division, select it in Division to edit instead of creating a duplicate.',
          ],
          'The event has the divisions needed for registration and session assignment.',
        ),
        step(
          'coach-sessions',
          'Schedule sessions, locations and groups',
          'coach-sessions',
          'Guided setup → Sessions',
          [
            'Choose the division and enter a session name that families and evaluators will recognize.',
            'Enter its start and end times in the timezone displayed. Add the location and capacity if you use a limit.',
            'Add an optional group and position where needed. Leave optional fields blank if they do not apply.',
            'Save the session. Return to Sessions and choose Add a new session to create additional sessions, then continue.',
          ],
          'The actual event schedule is saved separately from the registration window.',
        ),
        step(
          'coach-registration-form',
          'Build the public registration form',
          'coach-registration-form',
          'Guided setup → Registration',
          [
            'Name the form. Optionally enter the email that should receive new-registration notices; leave it blank to disable those notices.',
            'Select each question to edit its wording, help text, visibility and requirement. Essential built-in questions have their own constraints.',
            'Use Add field for extra questions. Choose a suitable field type and add dropdown choices when needed.',
            'Use the drag grips or arrow buttons to order the questions. Review which questions are optional before saving.',
          ],
          'Families will see the configured questions in the published registration flow.',
          'A changed form can require someone with an old form open to reload and review the current questions.',
        ),
        step(
          'coach-waiver',
          'Review the waiver and consent wording',
          'coach-waiver',
          'Registration editor → Waiver and consent',
          [
            'Choose the waiver question, or use Add waiver if your form needs another consent section.',
            'Enter the full wording families should read. The participation starter is editable; review and adapt it to your actual event.',
            'Check the Registrant preview. When a waiver is shown, families must accept it before submitting.',
            'Keep it visible if it is part of your registration requirements, then choose Save and continue.',
          ],
          'The registration form includes the wording and consent requirement you reviewed.',
        ),
        step(
          'coach-rubric',
          'Define what evaluators will score',
          'coach-rubrics',
          'Guided setup → Rubrics',
          [
            'Select a session and name its rubric.',
            'Add each category, its scoring scale, weight, and any description or scoring guidance. Use the available 1–5 or 1–10 scale.',
            'Make the category weights total 100. For example, Skating 60 and Game sense 40.',
            'Save and attach a rubric to every session. Return to Rubrics to configure the remaining sessions before review.',
          ],
          'Each session has a published rubric with valid weights.',
          'Existing evaluations retain their original rubric. A radar chart needs at least three scored criteria; shorter rubrics still show the scores and weighted total.',
        ),
        step(
          'coach-review',
          'Review the complete setup',
          'coach-review',
          'Guided setup → Review',
          [
            'Check the event name, sport, timezone, division count and session count.',
            'Resolve every listed blocker. Use the stage links to correct missing registration forms, sessions or rubrics.',
            'Check the actual dates, locations, questions and scoring instructions—not only the completion marks.',
            'Choose Ready to publish when the event is ready for families.',
          ],
          'The final publishing step is available.',
        ),
        step(
          'coach-publish',
          'Publish the event',
          'coach-publish',
          'Guided setup → Publish',
          [
            'Read the publishing screen and type the exact tryout name into its confirmation field.',
            'Choose Publish tryout and check that the overview shows Published.',
            'Remember that the registration opening and closing times still apply. Publishing a future event does not override its registration window.',
          ],
          'The event is published and its public registration link can be used when the window is open.',
        ),
        step(
          'coach-share',
          'Open and share the registration link',
          'coach-share',
          'Tryout overview → Registration link',
          [
            'Find Registration link near the bottom of the overview. Open public registration and check the organization, event and questions.',
            'Copy the public registration URL into your club’s normal communication channel, or share the displayed QR code.',
            'Send families the registration link, not your internal /app workspace address.',
            'Tell families the deadline, location and where to ask event questions.',
          ],
          'Parents can begin the correct event’s registration without needing staff access.',
          'Screenshot URLs and QR codes belong to a local demonstration. Always share the link generated for your own event.',
        ),
      ],
    },
    {
      id: 'coach-prepare',
      title: 'Prepare athletes & staff',
      description: 'Connect registrations, people and event-day responsibilities.',
      steps: [
        step(
          'coach-registrations',
          'Review registrations or add a participant',
          'coach-registrations',
          'Tryout → Prepare → Registration',
          [
            'Review Recent registrations and check that athletes are entered in the correct division.',
            'Use Find a returning athlete to reuse an existing record. Check the identity carefully before selecting it.',
            'For a new athlete, use Add a new participant and complete the required details and registration responses.',
            'If you import a CSV from Athletes, follow its template and review the import results. Check the tryout registration list afterward.',
          ],
          'Athletes have the correct registrations and existing records are reused where appropriate.',
        ),
        step(
          'coach-athlete-record',
          'Complete the athlete’s record',
          'coach-athlete-profile',
          'Athletes → choose an athlete',
          [
            'Review identity and sporting background. Use Edit sporting profile to add sport, positions, current team and relevant context.',
            'Use the tabs for Stats, Evaluations, Video, History, Development and Contacts.',
            'Correct name or birth-date errors through the available correction control. Keep each record about the correct athlete.',
            'Use the athlete report when you need a printable summary of the information you are authorized to see.',
          ],
          'Your staff can find the athlete’s history and context in one place.',
        ),
        step(
          'coach-assign-evaluators',
          'Assign evaluators to the right scope',
          'coach-staff',
          'Tryout → Prepare → Staff',
          [
            'Invite an evaluator if they are not already a member. Share the invitation link and confirm they have joined.',
            'Under Assign evaluation access, choose the evaluator and the appropriate whole-tryout, division, session or group scope.',
            'Choose Assign evaluator, then check Active evaluator grants.',
            'Have the evaluator sign in and open Evaluate to confirm that the expected sessions appear. Revoke assignments that are no longer needed.',
          ],
          'Evaluators see only the athletes and sessions assigned to them.',
        ),
        step(
          'coach-evaluator-preparation',
          'Have evaluators complete their preparation',
          'coach-evaluator-profile',
          'Evaluator account → Evaluate → View evaluator profile',
          [
            'Enter the evaluator’s sporting background, specialties, qualifications, experience and availability.',
            'Record any conflicts of interest and complete the preparation declarations shown.',
            'Review the event briefing and rubric together before scoring. Use calibration activities if the organizer has configured them.',
            'Save the profile and return to assigned sessions.',
          ],
          'The organizer has a record of the evaluator’s preparation and declared context.',
        ),
        step(
          'coach-family-access',
          'Link verified family accounts',
          'coach-participant-access',
          'Participant access → Link a participant account',
          [
            'Ask the parent or athlete to create and verify a participant account first.',
            'Verify their relationship to the athlete. Open Link a participant account, select the athlete, and enter the verified account email.',
            'Choose Guardian or Athlete and grant participant access. Check the saved link under Linked accounts.',
            'Review correction requests here and use Manage access when an existing link needs to change.',
          ],
          'The family account can see approved information for that linked athlete.',
          'Registration alone does not automatically grant portal access. Link each athlete separately for a family with multiple children.',
        ),
        step(
          'coach-eligibility',
          'Review eligibility and exceptions when needed',
          'coach-eligibility',
          'Tryout → Prepare → Eligibility',
          [
            'Enter the competition policy and requirements your event actually uses.',
            'Review the athlete evidence and record the eligibility review or exception in the available form.',
            'Resolve missing information with the family before relying on an eligibility decision.',
            'Use the saved review history to explain how a decision was reached.',
          ],
          'Eligibility reviews and exceptions are recorded alongside the event.',
          'This is an optional organizer workflow. Apply your competition’s requirements consistently.',
        ),
        step(
          'coach-stations',
          'Plan stations and rotations if your event uses them',
          'coach-stations',
          'Tryout → Prepare → Stations',
          [
            'Create a station and select the session it belongs to.',
            'Enter its name, location, time window, instructions, capacity and group label.',
            'Assign an appropriate evaluator and review coverage before the session starts.',
            'Keep station instructions aligned with the session rubric and tell staff how athletes will rotate.',
          ],
          'Your event has a shared station plan instead of separate staff notes.',
        ),
      ],
    },
    {
      id: 'coach-run',
      title: 'Run check-in & evaluations',
      description: 'Confirm arrivals, capture independent scores and watch completion.',
      steps: [
        step(
          'coach-check-in',
          'Check athletes in and assign numbers',
          'coach-check-in',
          'Tryout → Run event → Check-in',
          [
            'Choose the session and find the athlete using the available search or registration/QR lookup.',
            'Confirm the athlete’s identity and registration before checking them in.',
            'Assign or verify the tryout number using the controls shown. Avoid duplicate numbers within the configured scope.',
            'Check the saved check-in state and give the athlete their session or group instructions.',
          ],
          'Attendance and tryout numbers are visible to the event staff.',
        ),
        step(
          'coach-open-session',
          'Open the assigned scoring session',
          'coach-evaluator-sessions',
          'Evaluator account → Evaluate',
          [
            'Choose Open scoring session beside the correct session.',
            'Review your completion count and open Assigned athletes or Continue scoring.',
            'Check the athlete’s name, tryout number, division and session before entering a score.',
          ],
          'The evaluator is working in the intended session and athlete scorecard.',
        ),
        step(
          'coach-scoring',
          'Score the athlete and add useful notes',
          'coach-score-athlete',
          'Assigned session → athlete scorecard',
          [
            'Select one score for every required category, using the rubric’s definitions and scales.',
            'Add evidence-based private notes and relevant flags when needed. Keep observations about performance clear and specific.',
            'Review My Evaluation in the Athlete Profile panel. The weighted total appears when all required criteria are scored.',
            'Watch the save status. A local device draft is not the same as Saved on server; reconnect and wait for server confirmation before considering synchronization complete.',
          ],
          'The scorecard contains the evaluator’s own scores, notes and flags.',
          'With fewer than three scored criteria, the profile shows a score table instead of a radar polygon.',
        ),
        step(
          'coach-complete-scoring',
          'Complete each evaluation and verify the save',
          'coach-complete-evaluation',
          'Athlete scorecard → Complete evaluation',
          [
            'Check that every required category has a score and the draft is saved on the server.',
            'Choose Complete evaluation and verify the completed state. Use Save now only when it is enabled and a save is needed.',
            'Use Previous athlete or Next athlete to continue. Return to the session to check your progress.',
            'If a conflict or synchronization warning appears, read it and resolve it before continuing. Do not treat an unsynced device draft as a completed server record.',
          ],
          'Completed scorecards contribute to the permitted event evidence and progress counts.',
        ),
        step(
          'coach-profile-average',
          'Read the profile and evaluator average',
          'coach-average',
          'Athlete scorecard → Athlete Profile',
          [
            'Use My Evaluation to inspect your own criteria and weighted total.',
            'Choose Evaluator Average to view the authorized aggregate for this athlete, session and rubric.',
            'Check the number of evaluations behind the average. Missing or incomplete evidence should remain visible in your decision process.',
            'Use the individual criterion table when the profile has too few criteria for a radar chart.',
          ],
          'You can distinguish your own scoring from the available aggregate.',
          'An aggregate does not expose another evaluator’s private notes or individual scorecard.',
        ),
        step(
          'coach-live',
          'Watch event progress and fill coverage gaps',
          'coach-live',
          'Tryout → Run event → Live',
          [
            'Review registrations, check-ins and evaluation completion as the session progresses.',
            'Look for athletes with missing evaluations or insufficient coverage.',
            'Resolve the operational cause with your staff—for example, an incorrect assignment or an athlete who has not reached a station.',
            'Refresh the view as needed and confirm that completed work appears before moving to decisions.',
          ],
          'The organizer knows what is complete and which athletes still need attention.',
        ),
        step(
          'coach-performance',
          'Record measured performance when needed',
          'coach-performance',
          'Performance → Metric catalog → Create a metric',
          [
            'Define the metric before collecting results: name, sport, unit, measurement type and protocol.',
            'Choose whether higher or lower is better, and how repeated trials should be combined. Set valid bounds if needed.',
            'Save the metric, then use Record a measurement to enter the athlete, metric, time and trial details. Use Import CSV for an appropriate prepared file.',
            'Review the comparison filters and distinguish measured, verified results from unverified records.',
          ],
          'Measurements stay comparable because their units, protocol and trial history are recorded.',
        ),
      ],
    },
    {
      id: 'coach-decide',
      title: 'Review evidence & choose teams',
      description: 'Use the data to support a decision, then preserve the final roster.',
      steps: [
        step(
          'coach-rankings',
          'Review rankings with their coverage',
          'coach-rankings',
          'Tryout → Make decisions → Rankings',
          [
            'Choose the relevant filters and search for an athlete when needed.',
            'Read the score together with evaluation coverage and score range. A high score with little evidence needs context.',
            'Keep ties and unranked athletes visible in the review. Rankings do not automatically select the team.',
            'Select up to four athletes and choose Compare selected for a closer comparison.',
          ],
          'The decision group is reviewing scores and their supporting evidence together.',
        ),
        step(
          'coach-comparison',
          'Compare athletes side by side',
          'coach-comparison',
          'Rankings → select athletes → Compare selected',
          [
            'Check that you selected the intended athletes.',
            'Read the shared category scores, normalized profile and coverage information together.',
            'Use the comparison as evidence alongside position needs, observations and the event’s selection criteria.',
            'Return to Rankings to change the comparison selection.',
          ],
          'You can explain similarities, differences and evidence gaps without relying on the total alone.',
        ),
        step(
          'coach-build-roster',
          'Place athletes and record selection decisions',
          'coach-rosters',
          'Tryout → Make decisions → Rosters',
          [
            'Open the correct division’s draft roster. Review the athlete pool, teams and capacity.',
            'Use Move or the drag control to place an athlete on a team. Placement and selection status are separate choices.',
            'Select athletes, choose a Bulk decision, and review the proposed change before confirming it.',
            'Review every athlete’s status, team and supporting evidence. Resolve undecided records and capacity issues before finalizing.',
          ],
          'The draft reflects your staff’s intended team placements and decisions.',
        ),
        step(
          'coach-finalize',
          'Review and finalize the roster',
          'coach-finalize',
          'Rosters → Finalize roster',
          [
            'Review the final teams and decisions with the people responsible for selection.',
            'Choose Finalize roster and read the confirmation dialog.',
            'Check the acknowledgement that the roster becomes immutable, then choose Confirm finalization when it is correct.',
            'Verify the Finalized roster state. If your event still permits editing, use Create revision and record a reason for later corrections. A locked Single Tryout cannot create or edit a revision.',
          ],
          'An immutable roster snapshot and audit event are saved.',
          'Roster finalization does not send messages, start an export or complete the entire Single Tryout. Finish all divisions and communications before using Complete & lock tryout.',
        ),
        step(
          'coach-offers',
          'Prepare selection scenarios and portal offers',
          'coach-scenarios',
          'Tryout → Make decisions → Scenarios',
          [
            'Create a scenario with a clear name, target size and rationale.',
            'Add the intended athletes, roles, supporting rationale and response deadlines.',
            'Review the selections and capacity, then approve the scenario when it is ready.',
            'For linked families, approved scenarios appear as offers in the portal. Review the recorded responses and follow up when necessary.',
          ],
          'Linked families can respond to eligible pending offers before their deadline.',
          'Scenarios and portal offers are separate from the finalized roster and decision-email workflow.',
        ),
      ],
    },
    {
      id: 'coach-finish',
      title: 'Communicate, report & follow up',
      description: 'Close the loop with families and carry the work into the next event.',
      steps: [
        step(
          'coach-compose-message',
          'Prepare decision messages',
          'coach-messages',
          'Tryout → Communicate → Decision messages',
          [
            'Choose the finalized roster revision and the decision group you want to contact.',
            'Write the organization message. Protected athlete, decision and team facts come from the roster evidence.',
            'Choose Preview exact recipients. Read the recipient list and the exact rendered messages.',
            'Correct the source records or your message if anything is wrong, then generate a fresh preview.',
          ],
          'You can review the exact audience and message before anything is queued.',
        ),
        step(
          'coach-confirm-message',
          'Confirm the exact batch and track delivery',
          'coach-message-preview',
          'Decision messages → Exact recipient preview',
          [
            'Check every recipient and the final content. Do not infer the audience from the decision label alone.',
            'When ready to send, type SEND EXACT BATCH and use the confirmation button showing the exact recipient count.',
            'Watch Delivery status. Queued, sent, delivered and failed are different states.',
            'Investigate failures before retrying. If the preview expires or source data changes, generate and review a fresh preview.',
          ],
          'The exact reviewed batch is queued and its delivery can be tracked.',
          'The guide demonstrates the preview; no emails were sent to real families for these screenshots.',
        ),
        step(
          'coach-notices-fees',
          'Publish event updates and keep fees accurate',
          'coach-event-updates',
          'Tryout → Communicate → Notices & fees',
          [
            'Create a notice with a clear title, category and message. Publish it when it is ready for linked families.',
            'Use updates for arrival, equipment, schedule changes and reminders. Review the current wording before publishing.',
            'Maintain the fee ledger for each athlete, including amount, currency, due date and any recorded payments, refunds or waivers.',
            'Use receipt or approval references for adjustments, and tell families how your organization accepts payment.',
          ],
          'The portal shows published notices and recorded fee balances.',
          'A ledger entry does not collect money or prove a payment provider processed a transaction.',
        ),
        step(
          'coach-share-feedback',
          'Approve feedback for families',
          'coach-feedback',
          'Athletes → athlete → Evaluations or Development → report editor',
          [
            'Write clear observations, strengths, development areas and practical next steps.',
            'Record the observation context and use the review controls to approve the report when appropriate.',
            'Choose athlete-visible sharing only for information approved for the family. Save the report.',
            'Confirm that participant access is linked for the correct athlete; private and staff-only records remain separate.',
          ],
          'Approved athlete-visible feedback appears in the linked family portal.',
        ),
        step(
          'coach-reports',
          'Export or print the records you need',
          'coach-reports',
          'Reports, or Tryout → Reports',
          [
            'Choose the report that matches the task: event results, an athlete summary, scouting, program activity or exports.',
            'Check the scope, filters and roster revision before downloading or printing.',
            'Use Print / save PDF on supported report pages, then select a printer or Save as PDF in your browser.',
            'For a background export, check Export history and wait until the file is ready before downloading. Share reports only with the intended people.',
          ],
          'You have the correct report or export for the evidence and audience you selected.',
        ),
        step(
          'coach-next-event',
          'Start the next event and close your session',
          'coach-duplicate',
          'Tryouts → event overview → Duplicate tryout',
          [
            'Use Duplicate tryout when your plan permits copying setup, or create a new draft from Tryouts. Review the new event before publishing.',
            'Check its name, cycle, registration window, sessions, questions, waiver and rubrics before publishing.',
            'Verify the new event’s registrations and staff assignments. Reusing a setup does not mean the next event is already ready to run.',
            'Sign out when you finish on a shared device.',
          ],
          'The completed event remains available and the next event can be prepared deliberately.',
          'A Single Tryout license never transfers to the new event. It needs its own purchase or active subscription access, and the completed event stays locked.',
        ),
      ],
    },
  ],
  parents: [
    {
      id: 'parent-register',
      title: 'Register your athlete',
      description: 'Start with the organizer’s link. A family account is a separate step.',
      steps: [
        step(
          'parent-open-link',
          'Open the organizer’s registration link',
          'parent-registration',
          'The link or QR code shared by your club',
          [
            'Open the public registration link your organizer sent, or scan its QR code.',
            'Check the organization and event name before entering any information.',
            'Have the athlete’s details, guardian contact information and any requested answers ready.',
            'If registration has not opened, is closed or is unavailable, contact the organizer or return during the advertised window.',
          ],
          'You are on the correct event’s registration form.',
          'You do not need a staff organization account to complete public registration. Questions and the number of screens vary by event.',
        ),
        step(
          'parent-athlete-details',
          'Enter the athlete’s details',
          'parent-athlete-details',
          'Registration → Registration details',
          [
            'Enter the athlete’s first name, last name and date of birth exactly as requested.',
            'Provide a guardian phone number if shown. Complete all required fields; optional fields are labelled.',
            'Choose the division and position if the organizer’s form asks for them. A single eligible division may be selected automatically.',
            'Choose Continue. Correct any field-level errors before moving on.',
          ],
          'The athlete details are ready for the next part of registration.',
        ),
        step(
          'parent-guardian',
          'Enter guardian details and read consent',
          'parent-guardian-consent',
          'Registration → Additional details',
          [
            'Enter the guardian name and an email inbox you can access. The confirmation link is sent there.',
            'Answer the event’s remaining questions carefully.',
            'Read the entire waiver and consent wording. Accept it only if you understand and agree to it; ask the organizer about anything unclear.',
            'Choose Continue to review after completing the required answers and consent.',
          ],
          'Your contact details, answers and required consent are ready for review.',
          'An enabled waiver must be accepted before submitting. Do not assume another event’s consent covers this event.',
        ),
        step(
          'parent-review',
          'Review everything before submitting',
          'parent-review',
          'Registration → Review registration',
          [
            'Read the final summary, especially the athlete’s name, birth date and guardian email.',
            'Use Back to correct a mistake, then return to the review step.',
            'Choose Submit registration once and wait for the response. Avoid submitting another registration because the first is taking a moment.',
          ],
          'The app displays the registration confirmation screen or explains what needs attention.',
        ),
        step(
          'parent-confirmation-email',
          'Check for the confirmation email',
          'parent-confirmed',
          'Registration confirmation → your email inbox',
          [
            'When the screen says a confirmation link was queued, open the guardian email inbox used for registration.',
            'Look for the TryoutFlow registration confirmation message, including junk or spam.',
            'Open the one-time link in that email. Keep the link private.',
            'If the email does not arrive, ask the organizer to check the registration. Do not keep creating duplicates.',
          ],
          'The one-time confirmation page opens.',
          'The screenshot shows the confirmation you are working toward; your email application will look different. “Queued” is not the same as delivered or confirmed. Account verification and event-registration confirmation are separate.',
        ),
        step(
          'parent-confirm-registration',
          'Finish confirming the registration',
          'parent-confirmed',
          'One-time email link → Confirm registration',
          [
            'Follow the emailed link and complete the displayed bot-protection check if asked.',
            'Choose Confirm registration and wait for the message Your registration is confirmed.',
            'If the code expired, use the new-code option when shown and enter the same guardian email. If no code is available, return to the email or contact the organizer.',
            'Keep the event details and confirmation available for reference.',
          ],
          'The screen explicitly confirms the registration.',
          'Registration confirms your entry in the tryout process; it does not guarantee a team place.',
        ),
      ],
    },
    {
      id: 'parent-access',
      title: 'Set up your family portal',
      description: 'Get access to the athletes and updates your organizer shares with you.',
      steps: [
        step(
          'parent-create-account',
          'Create a participant account',
          'parent-sign-up',
          'Sign up → Athlete or family? Create a participant account',
          [
            'Choose the athlete/family account option, not Create an organization account.',
            'Use your own email and enter matching passwords that meet the displayed requirements.',
            'Create the account, open its verification email and follow the link.',
            'If you already have a verified account, use the participant sign-in link instead.',
          ],
          'You have a verified account for family portal access.',
          'This does not automatically register an athlete for an event or create a club workspace.',
        ),
        step(
          'parent-request-link',
          'Ask the organizer to link your athlete',
          'parent-link-pending',
          'Family portal → No athletes linked yet',
          [
            'Give the organizer the email of your verified participant account and identify the athlete you are responsible for.',
            'Let the organizer verify the relationship and grant the link.',
            'For more than one child, ask the organizer to link each athlete individually.',
            'Reload the portal after the organizer confirms the link. If the wrong athlete appears, stop and contact the organizer.',
          ],
          'Your linked athlete appears in the portal.',
          'An empty portal usually means the account has not been linked yet. Creating another club or registering again will not fix the link.',
        ),
        step(
          'parent-open-portal',
          'Sign in and check the athlete shown',
          'parent-portal',
          'Participant sign-in → Athlete and family portal',
          [
            'Sign in with the verified account the organizer linked.',
            'Check the organization, athlete name, sporting details and listed registrations.',
            'If you have several linked athletes, review each athlete’s section separately.',
            'Use the portal to read approved information and event updates; staff-only records are not included.',
          ],
          'You are viewing the correct athlete’s shared information.',
        ),
      ],
    },
    {
      id: 'parent-event',
      title: 'Prepare for tryout day',
      description: 'Check the latest instructions and know what to do on arrival.',
      steps: [
        step(
          'parent-schedule',
          'Read the schedule and event updates',
          'parent-schedule',
          'Family portal → Event updates and Session schedule',
          [
            'Read the event, session name, date, start/end times and timezone.',
            'Check the group assignment if one is shown. Use the latest published updates for arrival, location and equipment instructions.',
            'Contact the organizer if the schedule or group is missing or unclear.',
            'Recheck before leaving for the event in case the organizer has published a change.',
          ],
          'You know when to arrive and which instructions apply to your athlete.',
        ),
        step(
          'parent-check-in',
          'Check in with event staff',
          'parent-schedule',
          'At the venue → organizer’s check-in desk',
          [
            'Arrive at the time requested in the event updates and bring the required equipment.',
            'Give staff the athlete’s name and any confirmation or registration reference they requested.',
            'Confirm the assigned session, group and tryout number with staff.',
            'If the portal still says Check in with event staff, ask staff to verify attendance. Parents do not check themselves in through this portal.',
          ],
          'Staff confirm the athlete’s arrival and direct them to the correct activity.',
          'The screenshot shows the family schedule and check-in status; the staff check-in screen is separate.',
        ),
        step(
          'parent-fees',
          'Review any recorded event fees',
          'parent-fees',
          'Family portal → Event fees',
          [
            'Read the fee description, currency, amount charged and due date.',
            'Check the recorded paid, refunded and waived amounts and the remaining balance.',
            'Contact the organizer for payment instructions or to query a payment that has not been recorded.',
            'Keep your receipt and ask the organizer to correct the ledger if necessary.',
          ],
          'You know the recorded balance and how to follow up.',
          'This page displays the organizer’s fee ledger. It is not an online payment checkout.',
        ),
      ],
    },
    {
      id: 'parent-results',
      title: 'Read results & take the next step',
      description: 'Follow the organizer’s decisions, shared feedback and future opportunities.',
      steps: [
        step(
          'parent-feedback',
          'Read approved feedback and development advice',
          'parent-feedback',
          'Family portal → Approved feedback and development',
          [
            'Read the shared report, strengths, development areas and recommended next steps.',
            'Check any target date or video reference the organizer included.',
            'Ask the organizer to explain anything unclear and discuss an appropriate development plan with your athlete.',
            'If no feedback is shown, it may not have been approved for sharing yet. Contact the organizer about timing.',
          ],
          'You understand the feedback that the organizer has chosen to share.',
          'The family portal does not show other athletes’ records or private evaluator notes.',
        ),
        step(
          'parent-offer',
          'Review and respond to an offer',
          'parent-offer',
          'Family portal → Offers and next steps',
          [
            'Check the team/scenario name, offered role, response status and due date.',
            'Clarify any conditions with the organizer before choosing Accept offer or Decline offer.',
            'Make the intended choice while the offer is still pending and within its deadline.',
            'Wait for the saved response to appear. If you need to change a response or the buttons are unavailable, contact the organizer.',
          ],
          'The organizer can see the recorded offer response.',
          'An offer is shown only when the organizer has approved the relevant scenario and your account is linked. The event’s decision email may be a separate communication.',
        ),
        step(
          'parent-correction',
          'Request a correction to athlete information',
          'parent-correction',
          'Family portal → Corrections and requests',
          [
            'Open Corrections and requests under the correct athlete.',
            'Describe the incorrect information and the replacement clearly.',
            'Choose Submit correction request once and check that it was saved.',
            'Return to see whether the organizer marked it pending, resolved or declined, and read their response.',
          ],
          'The organizer receives a recorded correction request to review.',
          'A request does not immediately change the profile. For urgent event-day issues, contact staff directly.',
        ),
        step(
          'parent-next-event',
          'Register for another event',
          'parent-returning',
          'Family portal → Register for another event',
          [
            'Expand Register for another event under the athlete you want to register.',
            'Choose an available event link. The app can reuse that athlete’s name and birth date.',
            'Review all current questions, event details and consent before submitting. Complete that event’s confirmation process.',
            'If the desired event is not listed, ask the organizer for its public registration link.',
          ],
          'The same athlete can enter another event without creating an unnecessary duplicate profile.',
        ),
        step(
          'parent-print',
          'Save a copy and get help when needed',
          'parent-portal',
          'Family portal → Print / save PDF',
          [
            'Use Print / save PDF to open the browser print dialog and choose a printer or Save as PDF.',
            'Keep the saved file private because it contains athlete information.',
            'For schedules, registration corrections, fees, offers or access questions, contact the event organizer.',
            'For a forgotten password, use Forgot your password? on Sign in and follow the newest recovery email.',
          ],
          'You have a useful reference and know who can resolve event-specific questions.',
        ),
      ],
    },
  ],
};

export const guideLabels = {
  checkin: {
    title: 'Check-in staff',
    description:
      'From your invitation to confirmed arrivals, number exceptions and shift handover.',
    summary: 'Prepare · identify · check in · hand over',
    preparation:
      'Have your assignment, arrival schedule, numbering policy and organizer contact ready.',
    closing:
      'Your organizer can resolve registration corrections, placement questions and unconfirmed arrivals.',
    start: '/sign-in',
    startLabel: 'Sign in for check-in',
  },
  reviewers: {
    title: 'Reviewers',
    description: 'From review access to rankings, approved roster snapshots and recommendations.',
    summary: 'Review · compare · report · follow up',
    preparation:
      'Confirm your review assignment, event finalization state and the organizer’s review questions.',
    closing:
      'Give the organizer your evidence, recommendations and unresolved questions for the reviewed revision.',
    start: '/sign-in',
    startLabel: 'Sign in to review',
  },
  scouting: {
    title: 'Scouting & performance',
    description:
      'From prospect records to observations, measured trials, development and reporting.',
    summary: 'Observe · measure · develop · report',
    preparation:
      'Have scouting access, athlete references, observation sources and agreed test protocols ready.',
    closing:
      'Review outstanding reports, follow-ups and development goals with the organizer before the next observation.',
    start: '/sign-in',
    startLabel: 'Sign in for scouting',
  },
  evaluators: {
    title: 'Evaluators',
    summary: 'Prepare · score · sync · finish',
    preparation:
      'Have your invitation, assigned schedule, scoring guidance and evaluation device ready.',
    closing:
      'Your organizer can resolve assignment questions, arrange another observation and help with locked or incomplete evaluations.',
    description:
      'From your invitation to independent scoring, confirmed saves and a completed handoff.',
    start: '/sign-in',
    startLabel: 'Sign in to evaluate',
  },
  coaches: {
    title: 'Coaches & organizers',
    summary: 'Teams · single events · run · decide',
    preparation:
      'Have your schedule, divisions, registration questions, scoring criteria and staff list ready. Owners and administrators have organization tools; directors see tools within their event assignments.',
    closing:
      'Share the relevant guide with your staff and families so everyone knows their next step.',
    description:
      'From your first account to team workspaces, Single Tryout completion and family follow-up.',
    start: '/sign-up',
    startLabel: 'Create an organization account',
  },
  parents: {
    title: 'Parents & athletes',
    summary: 'Register · prepare · follow up',
    preparation:
      'Have the organizer’s registration link, athlete details and access to your email inbox ready.',
    closing:
      'Your event organizer is the right contact for registration, schedules, access, fees and team decisions.',
    description: 'From the registration link to schedules, feedback and your next event.',
    start: '/sign-up?purpose=participant',
    startLabel: 'Create a participant account',
  },
} as const;
