import type { GuideChapter, GuideStep } from './guide-content';

const step = (
  id: string,
  title: string,
  image: string,
  where: string,
  actions: string[],
  result: string,
  note?: string,
): GuideStep => ({ id, title, image, where, actions, result, note });

export const organizationTeamsGuide: GuideChapter = {
  id: 'coach-team-workspaces',
  title: 'Organization plan: separate team workspaces',
  description:
    'Run several teams under one Organization plan. Each team has its own coaches, athletes, tryouts and reports; organization managers can move between them.',
  steps: [
    step(
      'org-team-directory',
      'Open your organization’s team directory',
      'org-team-directory',
      'Organization workspace → Team workspaces',
      [
        'Sign in as the organization owner or administrator. In Switch workspace, choose the entry marked Organization.',
        'Open Team workspaces. Review each team’s tryouts, athlete records, coaches and completed evaluations.',
        'Use Open workspace, Manage coaches or View reports on the team you need. Check the team name before working with its records.',
      ],
      'You have one directory for all teams covered by the Organization plan.',
      'Team workspaces require Organization access. Pro, the 7-day Pro trial and Single Tryout do not include them. Directory totals count records in team workspaces; parent-workspace records are separate and an athlete in two teams counts in each team.',
    ),
    step(
      'org-create-team',
      'Create a separate workspace for a team',
      'org-create-team',
      'Team workspaces → Create a team workspace',
      [
        'Enter the team name, such as U18 Falcons.',
        'Review the generated workspace address. Use lowercase letters, numbers and hyphens, and choose a unique address if you customize it.',
        'Choose Create team workspace. Wait for the new team’s Home screen to open.',
      ],
      'The new team has its own workspace and inherits the organization’s plan.',
      'A team workspace is different from a roster team inside a tryout. Create it here to separate coaches and event data. Do not create a second standalone organization or start a second subscription.',
    ),
    step(
      'org-switch-team',
      'Switch teams before creating an event',
      'org-team-home',
      'Home → Switch workspace',
      [
        'Use Switch workspace to select the team you want to manage.',
        'Confirm the selected team and Part of organization label before creating a tryout, adding athletes or opening reports.',
        'Follow Build & publish a tryout below while inside this team. Repeat in the next team’s workspace as needed.',
        'Select the Organization entry to return to shared settings or the team directory.',
      ],
      'New records belong to the selected team, while existing records remain in their original workspace.',
      'Switching workspaces does not move or copy athletes, registrations or results. The selector lists only workspaces your account can access.',
    ),
    step(
      'org-invite-coach',
      'Invite coaches into the correct team',
      'org-team-coaches',
      'Team directory → Manage coaches, or team workspace → Members',
      [
        'Check the team name at the top of Members & permissions.',
        'Enter the coach’s email. Choose Administrator for someone who manages this team, or Member for staff who will receive event-specific duties.',
        'Choose Create invitation and privately share the generated link with the intended person. Have them accept using the invited email.',
        'Confirm the invitation is accepted. Add evaluator or other event assignments separately in that team’s tryout.',
      ],
      'The coach joins this team without receiving access to sibling teams.',
      'Invite at the team level for team-only access. Owners and administrators invited to the parent organization inherit access to every team. Entries marked Managed by organization must be managed in the parent workspace.',
    ),
    step(
      'org-coach-access',
      'Check the coach’s workspace access',
      'org-coach-workspace',
      'Invited coach account → team Home',
      [
        'Have the coach sign in with their own account and open the invited team.',
        'Check the team name and Switch workspace choices. A coach invited to one team should only see that team.',
        'If the coach also works with another team, invite them into that team separately.',
        'To remove team access, open that team’s Members page, change Access to Disabled and save. Remove event assignments when duties change.',
      ],
      'Each coach works only in the teams and event scopes assigned to them.',
      'This screenshot uses a real team-only demo coach account. It does not show the organization owner’s broader permissions.',
    ),
    step(
      'org-shared-settings',
      'Maintain shared branding and defaults',
      'org-shared-defaults',
      'Organization workspace → Settings',
      [
        'Switch to the parent Organization workspace and open Settings.',
        'Review athlete terminology, sport defaults and quick tags. Save the settings you want teams to share.',
        'Use Organization logo to upload or replace the club logo when your role permits it.',
        'Return to a team workspace and check the inherited settings.',
      ],
      'Teams share the parent organization’s branding and program defaults.',
    ),
    step(
      'org-team-settings',
      'Review a team’s inherited settings',
      'org-inherited-defaults',
      'Team workspace → Settings',
      [
        'Read the shared-settings notice to confirm which organization manages the defaults.',
        'Keep terminology, sports, tags and branding changes in the parent organization.',
        'Review the team timezone separately and save a correction if needed. Check the timezone when scheduling that team’s sessions.',
      ],
      'The team keeps consistent organization defaults while using its own timezone.',
    ),
    step(
      'org-central-billing',
      'Keep billing with the organization owner',
      'org-team-billing',
      'Team workspace → Billing',
      [
        'Open Billing inside a team. Confirm that the page says Covered by your organization.',
        'Organization managers can follow Open organization billing. Team-only coaches should contact the organization owner for billing changes.',
        'Do not start a separate team subscription or trial; the parent Organization plan provides team access.',
        'If Organization access expires or changes, ask the owner to review billing. Existing team records are retained, but plan-dependent tools may be unavailable.',
      ],
      'One organization billing account covers its team workspaces.',
      'Paid checkout is currently marked coming soon. The screenshots demonstrate already provisioned demo Organization access, not a completed live payment.',
    ),
  ],
};

export const singleTryoutGuide: GuideChapter = {
  id: 'coach-single-tryout',
  title: 'Single Tryout: prepare, run & lock one event',
  description:
    'One purchase covers one event ID. Prepare carefully before publishing, finish work within the closing window, then keep the completed results as a read-only record.',
  steps: [
    step(
      'single-plan',
      'Check what Single Tryout covers',
      'single-plan',
      'Pricing → Single Tryout Pro',
      [
        'Review the one-time US$34.99 price and the features shown for Single Tryout Pro.',
        'Use this plan for one event. For repeat events, compare Pro; for separate team workspaces, compare Organization.',
        'When checkout is available, select the intended tryout in Billing before purchasing. Confirm that access has been granted to that event before publishing.',
      ],
      'You know which event the license covers and when its editing access ends.',
      'Live paid checkout is currently coming soon. These screenshots use a provisioned local demo license; they do not show a completed payment. The 7-day no-card trial belongs to Pro. Single Tryout excludes organization-wide scouting and historical scorecards.',
    ),
    step(
      'single-draft',
      'Finalize the draft’s identity and registration dates',
      'single-draft',
      'Tryouts → new draft → Basics',
      [
        'Create the event in the intended workspace and select the correct cycle or season.',
        'Review its name, sport, timezone and registration opening and closing times. Correct mistakes while it is still a draft.',
        'Complete the divisions, registration form, waiver and rubrics using Build & publish a tryout below.',
        'Check that the Single Tryout notice appears for this licensed event.',
      ],
      'The draft describes the one event you intend to run.',
      'Publishing freezes the event identity, divisions, positions, registration dates and session schedule. Make any rescheduling or identity corrections before publishing.',
    ),
    step(
      'single-schedule',
      'Keep all sessions inside the event window',
      'single-sessions',
      'Guided setup → Sessions',
      [
        'Enter every session, division, location and start/end time before publishing.',
        'Keep the span from the first session’s start to the last session’s end within 14 days.',
        'Set registration to close no later than the last session. Check every session time in the event timezone.',
        'Allow time to finish scores, selections and messages: editing closes 7 days after the last session.',
      ],
      'The schedule meets the Single Tryout limits and has a fixed closing deadline.',
      'Leaving an event in progress does not extend the deadline. Additional or rescheduled sessions cannot be added after publication to reuse the purchase.',
    ),
    step(
      'single-publish',
      'Review once more, then publish',
      'single-publish',
      'Guided setup → Review → Publish',
      [
        'Resolve every setup blocker and double-check the name, season, divisions, registration window and all session dates.',
        'Read the Single Tryout notice. Confirm that these are the event details you want to lock.',
        'Type the exact event name when requested and choose Publish tryout.',
        'Open the overview and confirm that the fixed-event notice and editing deadline are shown.',
      ],
      'The event is published and its identity and schedule are permanently attached to this license.',
    ),
    step(
      'single-run',
      'Run the event and finish the wrap-up work',
      'single-sealed',
      'Published tryout → Overview',
      [
        'Check the editing deadline shown in the Single Tryout notice; the notice displays its time in UTC.',
        'Use the event’s registration, check-in, evaluation, ranking and roster tools for this tryout.',
        'Finish scores, roster decisions, any needed roster revisions, fees and new messages before locking or before the deadline.',
        'Finalizing an individual roster is separate from completing the whole tryout. Review all divisions, finish communications and collect any pending portal-offer responses you need before locking.',
      ],
      'The event’s operational work is finished before its editing window closes.',
      'The published event’s name, season and schedule cannot be changed. If the event details are wrong, contact support; there is no self-service reopening or rescheduling that transfers the license.',
    ),
    step(
      'single-complete',
      'Confirm Complete & lock only when finished',
      'single-complete',
      'Tryout → Overview → Finished this tryout?',
      [
        'Review all scores, selections, roster revisions and messages. Make any permitted corrections now.',
        'Read the permanent-lock warning and check the acknowledgement that the work is finished and cannot be undone.',
        'Choose Complete & lock tryout.',
        'Wait for the locked overview to appear before leaving the page.',
      ],
      'All further event editing stops immediately.',
      'Only an authorized manager can complete the tryout. If you do not complete it manually, editing still locks automatically 7 days after the last scheduled session.',
    ),
    step(
      'single-locked',
      'Recognize the permanent read-only state',
      'single-locked',
      'Completed or automatically locked tryout → Overview',
      [
        'Look for Tryout locked · results preserved.',
        'Use View results & exports to return to the retained evidence.',
        'Do not try to change dates, reset the status, delete sessions or buy the same event again to reopen it. These requests are blocked by the server.',
      ],
      'The original event stays preserved and cannot become a new event under the same purchase.',
      'New registrations, score changes, roster changes and new messages are blocked. Messages already queued may finish delivery, and staff access can still be revoked. Upgrading the plan does not reopen this completed event.',
    ),
    step(
      'single-results',
      'Read and export the completed results',
      'single-results',
      'Locked tryout → View results & exports → Reports',
      [
        'Confirm the event name and review its athlete, evaluation and finalized-roster totals.',
        'Choose Download athletes CSV, Download evaluations CSV or the available finalized-roster download.',
        'Keep each export private and share it only with the intended people. Other staff can only read results allowed by their role.',
      ],
      'You keep access to the licensed event’s retained results after editing has ended.',
      'The illustrated report uses a completed example with saved athletes and scores. Exporting does not unlock or alter the event.',
    ),
    step(
      'single-next-event',
      'Create a new event for the next tryout',
      'single-new-event',
      'Tryouts → Create draft',
      [
        'Create a new draft with its own name, season and dates; leave the completed event intact.',
        'Arrange a new Single Tryout purchase for the new event when checkout is available, or use an active Pro or Organization subscription.',
        'If your plan offers Duplicate tryout, use it only as a setup shortcut and review the new draft. It does not copy the one-time license.',
        'Confirm the new event’s access before publishing.',
      ],
      'The next event has its own identity and authorization; the previous event remains read-only.',
    ),
  ],
};
