import type { GuideChapter, GuideStep } from './guide-content';
const step = (
  id: string,
  title: string,
  image: string,
  where: string,
  actions: string[],
  result: string,
  note?: string,
): GuideStep => ({ id: `reviewer-${id}`, title, image, where, actions, result, note });
export const reviewerGuide: GuideChapter[] = [
  {
    id: 'reviewer-access',
    title: 'Join and confirm review access',
    description: 'Reviewers work within an assigned scope and the event’s finalization state.',
    steps: [
      step(
        'invitation',
        'Accept your invitation and sign in',
        'evaluator-invitation',
        'Invitation → Sign in → Accept invitation',
        [
          'Open the organizer’s invitation and sign in with the invited email. If necessary, register and verify the account, then return to the invitation.',
          'Choose Accept invitation for the correct organization. Ask for a replacement link if it has expired.',
          'Ask the organizer to grant Reviewer access for the event or narrower scope you will review. Organization membership alone does not create that assignment.',
          'Use your own account so the app can apply your permissions consistently.',
        ],
        'Your account is ready for the assigned review workflow.',
      ),
      step(
        'workspace',
        'Find the assigned event and confirm your remit',
        'reviewer-workspace',
        'My workspace → Rankings / Rosters / Reports',
        [
          'Confirm the organization and Reviewer role, then locate the assigned event links under My workspace. On a phone, open navigation first.',
          'Agree with the organizer which event, division, athletes and review questions you are responsible for.',
          'Treat the reviewer role as an evidence-review role. Active roster building and finalization require an authorized organizer or director.',
          'When multiple event links look alike, verify the event with the organizer before using a report or drawing conclusions.',
        ],
        'You know the intended review scope and who owns final decisions.',
      ),
      step(
        'availability',
        'Understand why rankings may not be available yet',
        'reviewer-rankings-access',
        'Rankings → Access message',
        [
          'Open Rankings for your assignment. Reviewer rankings require the event itself to be finalized.',
          'A finalized roster and a finalized event are separate states. Ask the organizer to confirm both when access is unclear.',
          'If Rankings access denied appears, check your account and assignment, then ask the organizer whether review access is ready.',
          'Do not request someone else’s login to work around an access restriction.',
        ],
        'You can distinguish an unavailable review stage from missing scores.',
        'The denied example is a published fall event. The available ranking examples use a finalized spring event.',
      ),
    ],
  },
  {
    id: 'reviewer-evidence',
    title: 'Read rankings and compare evidence',
    description: 'Use completed evaluations, coverage and context together.',
    steps: [
      step(
        'filters',
        'Select the correct ranking filters',
        'reviewer-filters',
        'Rankings → Filter rankings',
        [
          'Open Filter rankings and choose the relevant division, position, session or group.',
          'Use Completion to distinguish complete coverage, partial coverage and no completed evaluations. Check any minimum evaluator requirement.',
          'Choose the sort that answers your review question, such as overall rank, category, coverage or evaluator spread, then apply the filters.',
          'Use Search athletes for an individual name. Reset filters or clear the search if an expected athlete disappears.',
        ],
        'You are reviewing the intended group of athletes with known filters.',
      ),
      step(
        'coverage',
        'Read scores with their coverage',
        'reviewer-rankings',
        'Rankings → Player rankings',
        [
          'Read rank and overall score alongside the completed/expected evaluation count and coverage percentage.',
          'Check the score range for differences in completed observations; a narrow range based on one evaluation is limited evidence.',
          'Treat Unranked or No completed score as missing completed evidence, not a score of zero.',
          'Bring missing observations, ties and unusual differences to the review discussion. Rankings do not automatically select athletes.',
        ],
        'Your review accounts for the strength and limits of the evidence.',
        'The example intentionally includes one partially covered athlete and one unranked athlete.',
      ),
      step(
        'compare',
        'Compare two to four athletes',
        'reviewer-comparison',
        'Rankings → Compare selected',
        [
          'Tick the comparison boxes for two to four athletes and choose Compare selected.',
          'Check the selected identities and compare overall scores, positions, coverage, ranges and available category/session evidence.',
          'A radar overlay requires at least three matching scored criteria from the same form version. Use the table when an overlay is unavailable.',
          'Choose Back to rankings to change the selection or filters.',
        ],
        'You can explain similarities, differences and missing evidence between the selected athletes.',
      ),
      step(
        'discussion',
        'Prepare a review recommendation',
        'reviewer-comparison',
        'Athlete comparison → Review discussion',
        [
          'Record the event, athlete references, filters and observation coverage supporting your recommendation using the organizer’s agreed review process.',
          'Separate observed strengths from assumptions and identify where another observation would improve confidence.',
          'Consider the event’s stated criteria and role needs alongside the scores.',
          'Give your recommendation to the authorized decision makers; this comparison screen does not submit a roster decision.',
        ],
        'The organizer receives a recommendation with clear supporting evidence and limitations.',
      ),
    ],
  },
  {
    id: 'reviewer-reports',
    title: 'Use the approved roster snapshot',
    description: 'Reports provides the reviewer’s authorized immutable export.',
    steps: [
      step(
        'report',
        'Open the approved final report',
        'reviewer-report',
        'My workspace → Reports',
        [
          'Open Reports for the correct assigned event and read the access explanation.',
          'Look for Download finalized roster CSV. Reviewer report access is limited to the immutable roster snapshot offered here.',
          'If the verified snapshot is unavailable, ask an authorized manager to create and finalize an appropriate new revision.',
          'Do not assume a newer roster has replaced the offered snapshot if the page warns that another finalized roster lacks a verified export.',
        ],
        'You know which approved roster snapshot is available for review.',
        'The example offers a verified revision and separately warns that another finalized snapshot is unavailable.',
      ),
      step(
        'download',
        'Download and review the finalized roster',
        'reviewer-report',
        'Reports → Download finalized roster CSV',
        [
          'Choose Download finalized roster CSV and open the downloaded file in your spreadsheet application.',
          'Confirm the event and roster revision information with the organizer before using the file for a review meeting.',
          'Compare the recorded team placements and decision statuses with the review remit. Keep notes about discrepancies separate from the immutable export.',
          'If the download fails or access has changed, return to Reports and ask the organizer to confirm the available revision.',
        ],
        'You have the authorized finalized roster for your review.',
        'The local walkthrough verified that the download starts. Your spreadsheet application will look different.',
      ),
      step(
        'roster-access',
        'Handle an unavailable roster workspace',
        'reviewer-roster-unavailable',
        'Rosters → Unavailable page',
        [
          'If Rosters opens an unavailable page, return to your assigned event’s Reports link.',
          'Use the approved CSV for reviewer access rather than assuming you can enter the staff roster-building workspace.',
          'Tell the organizer which event and page failed, especially when Reports and Rosters behave differently.',
          'Do not alter a roster, create a revision or send family decisions unless you have the appropriate role and the organizer’s instructions.',
        ],
        'You can continue with the approved review artifact and report the navigation issue.',
        'In the current local reviewer walkthrough, the Rosters link returned this unavailable page while Reports provided a valid CSV. This is an observed limitation, not a required user action.',
      ),
    ],
  },
  {
    id: 'reviewer-close',
    title: 'Close the review loop',
    description:
      'Communicate findings and preserve the boundary between recommendations and decisions.',
    steps: [
      step(
        'handoff',
        'Hand findings back to the organizer',
        'reviewer-report',
        'Review meeting → Organizer follow-up',
        [
          'Give the organizer the reviewed event and revision, your recommendations, unresolved discrepancies and evidence gaps.',
          'Agree who will resolve each outstanding question and when you should review again.',
          'Have an authorized manager handle changes through the normal roster revision and communication workflows.',
          'If you are asked to review a later version, obtain its approved report again; a previously downloaded CSV will not update itself.',
        ],
        'The organizer knows what was reviewed and what still requires action.',
      ),
      step(
        'signout',
        'Finish securely and sign out',
        'evaluator-sign-out',
        'Workspace → Sign out',
        [
          'Keep downloaded rosters and review notes within the organizer’s approved storage and audience.',
          'Close any report on a shared device and sign out of TryoutFlow.',
          'Verify that the sign-in page appears.',
          'For later corrections or access questions, contact the organizer with the event and revision reference.',
        ],
        'Your review is complete and your account session is closed.',
      ),
    ],
  },
];
