import type { GuideChapter, GuideStep } from './guide-content';
const step = (
  id: string,
  title: string,
  image: string,
  where: string,
  actions: string[],
  result: string,
  note?: string,
): GuideStep => ({ id: `scouting-${id}`, title, image, where, actions, result, note });
export const scoutingGuide: GuideChapter[] = [
  {
    id: 'scouting-access',
    title: 'Join the scouting workspace',
    description: 'Start with an authorized account and the correct athlete record.',
    steps: [
      step(
        'invitation',
        'Join the organization and confirm scouting access',
        'evaluator-invitation',
        'Invitation → Sign in → Accept invitation',
        [
          'Open the organizer’s invitation and use the invited email to sign in. If necessary, create and verify the account, then return to the invitation.',
          'Accept the invitation for the correct organization and ask the organizer to confirm your scouting access.',
          'Scouting access and event evaluation assignments are separate. An evaluator assignment alone does not give you every scouting or performance tool.',
          'Agree which athletes, information sources and follow-up work you are responsible for.',
        ],
        'You have the right account and understand the intended work.',
      ),
      step(
        'workspace',
        'Find Scouting and Performance',
        'scout-workspace',
        'My workspace → Scouting / Performance',
        [
          'Sign in and check the organization name. Look for Scouting, Performance and Search athletes in the navigation.',
          'Open Scouting for prospects, reports and development work. Open Performance for defined tests and measured trials.',
          'On a phone, open the navigation menu first. If the links are missing, ask the organizer to check your scouting access.',
          'A scouting-only account may be labelled Member. Use the available tools and your assigned responsibilities to understand your access.',
        ],
        'You can find the two connected workspaces.',
        'These screenshots use a scouting-only member account; organizer accounts have additional navigation.',
      ),
      step(
        'find',
        'Find the athlete before creating new records',
        'scout-pipeline',
        'Scouting → Pipeline → Search',
        [
          'Search the pipeline by name, position, club or tag and choose Apply filters.',
          'Check the athlete’s identity and existing sporting background. Open the existing profile when it is the correct person.',
          'If the athlete is not present, ask an authorized organizer to create or import the athlete, then return to the pipeline.',
          'Use Add prospect only if your account has athlete-creation permission. Scouting-only access can review an existing profile but does not grant that permission.',
        ],
        'Your observations will be attached to the correct existing athlete.',
        'The Add prospect link was unavailable to the scouting-only example account; a manager must handle creation. Avoid duplicate profiles.',
      ),
      step(
        'profile',
        'Review and complete the sporting profile',
        'scout-profile-editor',
        'Pipeline → Athlete → Edit sporting profile',
        [
          'Open the athlete and review Overview, Stats, Evaluations, Video, History and Development as available.',
          'Choose Edit sporting profile to update sport, positions, club, competitive level, dominant side and relevant background.',
          'Use Watchlist tags consistently with the team’s naming convention and select the current recruitment stage.',
          'Choose Save changes and wait for Saved. Report identity corrections to an authorized organizer rather than replacing the athlete with a duplicate.',
        ],
        'The athlete’s sporting context supports later observations and comparisons.',
      ),
    ],
  },
  {
    id: 'scouting-pipeline',
    title: 'Organize prospects and next actions',
    description: 'Keep recruitment stages, watchlists and follow-ups current.',
    steps: [
      step(
        'stage',
        'Update recruitment stage and tags',
        'scout-stage',
        'Pipeline → Update stage',
        [
          'Find the intended athlete and choose Update stage on their row.',
          'Select the stage that reflects the actual recruitment work, such as Observe, Follow up, Evaluating or Monitor.',
          'Add useful watchlist tags separated by commas, then choose Save changes and confirm the saved state.',
          'A pipeline stage is organizational context. Marking Selected here does not finalize a tryout roster or send an offer.',
        ],
        'The pipeline reflects the current recruitment stage without implying a separate roster action.',
      ),
      step(
        'watchlist',
        'Create a watchlist entry',
        'scout-watchlist',
        'Scouting → Watchlists → Add watchlist entry',
        [
          'Open Watchlists and choose Add watchlist entry.',
          'Select the athlete, enter a recognizable Watchlist name and describe why this athlete should be revisited.',
          'Record the observation context where useful, then select the appropriate Status and Audience.',
          'Save the entry, confirm Saved, and check that the entry appears in the intended list. Use filters to return to it later.',
        ],
        'The athlete has a recorded reason for continued observation.',
      ),
      step(
        'followup',
        'Assign a specific follow-up',
        'scout-followup',
        'Scouting → Follow-ups → Add follow-up',
        [
          'Select the athlete and use a title that describes the next action, such as Observe scanning under pressure.',
          'Add a due date and select Assigned to so responsibility is explicit. Confirm the person can access the record’s audience.',
          'Use Notes to explain what should be observed and what evidence should be brought back. Set the appropriate status, usually Active for work ready to begin.',
          'Save and verify the entry. Tell the assigned person through your agreed process; recording an assignment is not proof of an email or notification.',
        ],
        'The next observation has an owner, due date and expected outcome.',
      ),
    ],
  },
  {
    id: 'scouting-observations',
    title: 'Record and review scouting evidence',
    description: 'Attach specific observations to the right athlete, context and audience.',
    steps: [
      step(
        'context',
        'Start a report with observation context',
        'scout-report-context',
        'Scouting → Reports → Add report',
        [
          'Choose Add report and select the athlete. Give the report a title that identifies its purpose.',
          'Choose the actual observation method: Live, Video, Training or Other.',
          'Add the event, opponent or location and the skill or criterion the evidence supports.',
          'Record the observation time using the displayed UTC convention and identify the event or source. Do not substitute the date you wrote the report for the observation date.',
        ],
        'The report can be traced to a particular observation and athlete.',
      ),
      step(
        'assessment',
        'Describe strengths, development areas and next steps',
        'scout-assessment',
        'Report editor → Assessment',
        [
          'Describe specific strengths and the actions that support them, rather than only using general praise or a score.',
          'Record development areas with enough context to guide another observation or practice task.',
          'Use Role fit and recommended next step for your recommendation, and Notes for relevant limits or circumstances.',
          'Separate what you observed from what you inferred. Avoid treating a single practice observation as a final selection decision.',
        ],
        'The report contains evidence and an actionable recommendation.',
      ),
      step(
        'sharing',
        'Choose review status and audience deliberately',
        'scout-report-review',
        'Report editor → Review & sharing',
        [
          'Use Draft while preparing the report and In review when it is ready for the organizer’s review process.',
          'Choose Only me for your private record, Scouting staff for authorized colleagues, or Approved athlete feedback for material intended for the family after approval.',
          'Review the text for the intended audience before saving. Do not assume selecting an audience alone publishes it to a family.',
          'Ask an authorized organization manager to review and approve athlete-facing feedback. A scouting-only account cannot grant itself that approval.',
        ],
        'The saved record has an explicit audience and review state.',
        'The example report is In review and shared with scouting staff. It has not been approved for athlete feedback.',
      ),
      step(
        'save',
        'Save and verify the report',
        'scout-report-saved',
        'Report editor → Save report',
        [
          'Choose Save report and wait for Saved and the confirmation that the workspace is up to date.',
          'Close the editor and find the report card. Check its title, athlete, author, status and audience.',
          'If an error or conflicting update is reported, keep your work available, read the message and resolve it before leaving.',
          'Use Add another only for a genuinely new observation; do not duplicate a report because the first response was unclear.',
        ],
        'The report is stored and its review state is visible.',
      ),
      step(
        'video',
        'Attach a video reference and useful clip range',
        'scout-video',
        'Scouting → Video evidence → Add video reference',
        [
          'Select the athlete, enter a title and set Observation method to Video when appropriate. Record the event and supported skill.',
          'Enter an HTTPS link to footage your intended audience is allowed to view. Use Clip start and Clip end in seconds to identify the relevant moment.',
          'Explain what the clip supports in Notes, choose the appropriate Status and Audience, then save and confirm the result.',
          'Verify access to the source with the intended viewers. A saved reference does not upload the video or change its hosting permissions.',
        ],
        'The record connects a specific video moment to the athlete and observation.',
        'The screenshot shows the editor’s clip fields. No real athlete footage was uploaded or linked for this example.',
      ),
      step(
        'goal',
        'Turn observations into a development goal',
        'scout-development',
        'Scouting → Development → Add development goal',
        [
          'Select the athlete and name the skill or behavior to improve.',
          'Enter a due date and owner. In Goal, success measure and progress, describe the practice action and how improvement will be checked.',
          'Choose a status and audience that match the plan’s readiness, then save and verify the result.',
          'Agree the plan with the responsible coach. Review the goal after the planned observation and update its progress using Edit goal.',
        ],
        'The athlete has a specific, reviewable development action.',
        'The example is a staff draft. A saved draft is not automatically delivered to the athlete.',
      ),
    ],
  },
  {
    id: 'scouting-measurements',
    title: 'Define tests and record measurements',
    description: 'Use consistent units, protocols, trial states and source information.',
    steps: [
      step(
        'lab',
        'Check the metric catalog before measuring',
        'performance-lab',
        'Performance → Metric catalog',
        [
          'Open Performance and review the existing metric catalog before creating a test.',
          'Match the sport, unit, protocol, performance direction and method for combining trials to the test you will run.',
          'Use the existing metric only when the protocol is genuinely the same. Use Create a metric or an editable sport template for a new protocol.',
          'Agree the procedure and equipment with staff before collecting results.',
        ],
        'Everyone is measuring the same test using the same definition.',
      ),
      step(
        'metric',
        'Define the metric, units and scoring direction',
        'performance-metric',
        'Metric catalog → Create a metric',
        [
          'Enter a clear Metric name, Sport and Unit, such as seconds for a timed test.',
          'Choose Measurement type. Use Ratio for successes out of attempts and the appropriate numeric type for other tests.',
          'Set Better performance means to Higher value, Lower value or Descriptive only as appropriate.',
          'Choose how repeated trials should be combined: Best, Mean or Latest. This changes the comparison result, so agree it before data collection.',
        ],
        'The metric has an unambiguous unit, direction and aggregation method.',
      ),
      step(
        'protocol',
        'Document the protocol and save the metric',
        'performance-protocol',
        'Metric editor → Measurement protocol',
        [
          'Describe equipment, distance, start conditions, timing method and anything required to reproduce the test.',
          'Set lowest and highest valid values if sensible for this protocol. Leave optional bounds blank when they would not be meaningful.',
          'Choose Save metric and wait for confirmation. Check the metric’s catalog card.',
          'Create a new metric when the protocol changes so old and new observations are not silently mixed.',
        ],
        'The saved protocol is available for individual entries and CSV imports.',
        'The skating test shown is a fictional example, not a prescribed training standard.',
      ),
      step(
        'trial',
        'Enter the athlete, metric and attempt result',
        'performance-measurement',
        'Performance → Record a measurement',
        [
          'Choose the correct athlete and Metric and protocol. Select a session when one is available and applicable; otherwise record an independent observation.',
          'Select Attempt status. Use Valid for a usable measurement, or the appropriate Invalid, Not observed or Did not participate state.',
          'Enter the value in the metric’s unit. For ratios, enter successes and attempts instead.',
          'Record the Trial number and measured time using the displayed UTC convention. Missing performance is not a measured zero.',
        ],
        'The entry describes one identifiable attempt using the correct protocol.',
      ),
      step(
        'source',
        'Record the source and confirm the save',
        'performance-source',
        'Measurement editor → Source / operator / device',
        [
          'Enter the source, operator or device so staff can understand where the result came from.',
          'Check Verified against source only after doing that verification. Leave it unchecked when the source has not been confirmed.',
          'Record relevant conditions or a correction reason, then choose Save measurement.',
          'Wait for Saved and confirm the result appears in the athlete’s Stats or the performance comparison.',
        ],
        'The stored result carries its source and honest verification state.',
        'The example result is deliberately unverified.',
      ),
      step(
        'history',
        'Review trials and correct a recorded measurement',
        'performance-correction',
        'Athlete → Stats → Correct a recorded trial',
        [
          'Open the athlete’s Stats and check the trial history, including date, trial, result and source.',
          'Expand Correct a recorded trial and open the exact metric, date and trial that needs correction.',
          'Check the source before changing the value or verification state, and explain the correction in Conditions or correction reason.',
          'Save and verify the updated history. Record a genuinely new attempt as a new trial rather than overwriting an earlier performance.',
        ],
        'Corrections are deliberate and new attempts remain distinguishable from old ones.',
      ),
    ],
  },
  {
    id: 'scouting-imports',
    title: 'Import and compare performance data',
    description: 'Review every import and interpret comparisons within their selected cohort.',
    steps: [
      step(
        'csv',
        'Prepare a measurement CSV',
        'performance-import',
        'Performance → Import CSV',
        [
          'Prepare one metric per file. Include athlete_id or a unique athlete name, measured_at as an ISO timestamp with timezone, source and value.',
          'For a ratio metric, use successes and attempts. Optional columns include trial, status, verified and note.',
          'Use an explicit status such as not_observed for missing performance. Check units, decimal values, timestamps and athlete identity before uploading.',
          'Select the matching Metric and the appropriate Session or Independent observation, then choose CSV file.',
        ],
        'The file is ready for validation against a known metric and athlete set.',
      ),
      step(
        'preview',
        'Review the import before saving',
        'performance-import-preview',
        'Import measurements → Import preview',
        [
          'Wait for the preview and inspect the athlete, result, date and validation state on each row.',
          'Correct invalid rows, ambiguous athlete names or mismatched units in the source file, then choose the corrected file again.',
          'Check the selected metric and protocol against the data. A preview is not confirmation that anything has saved.',
          'When the reviewed rows are correct, choose Import followed by the displayed measurement count.',
        ],
        'Only the reviewed data proceeds to the import action.',
      ),
      step(
        'import-result',
        'Confirm import completion and reconcile results',
        'performance-import-complete',
        'Import measurements → Saved status',
        [
          'Wait for the message stating how many measurements saved and the Imported button state.',
          'If any rows failed or the outcome is unclear, read the result and investigate before uploading the entire file again.',
          'Return to Performance lab and inspect the intended athletes and trials to confirm the saved results.',
          'Keep the source file available for reconciliation. Avoid creating duplicate measurements by repeating an already successful import.',
        ],
        'The imported rows have a confirmed outcome in the performance lab.',
        'The local example imported one fictional measurement successfully.',
      ),
      step(
        'cohort',
        'Filter a meaningful comparison cohort',
        'performance-filters',
        'Performance → Filter the comparison cohort',
        [
          'Expand Filter the comparison cohort and select relevant sport, metric, position, session, level and date filters.',
          'For age filters, set Age as of deliberately. Athletes with unknown birth dates are excluded from age-filtered results.',
          'Choose Apply filters and read the resulting cohort count. Use Clear filters to recover the broader view when needed.',
          'Compare compatible protocols and observation periods. Record the filter context when sharing a conclusion.',
        ],
        'The comparison uses a defined, relevant set of athletes.',
      ),
      step(
        'comparison',
        'Interpret results, trials and percentiles',
        'performance-comparison',
        'Performance → Performance comparison',
        [
          'Read the metric’s protocol, unit, performance direction and aggregation method above the table.',
          'Compare Result and Trials together and pay attention to Includes unverified results.',
          'Percentiles require at least five athletes with valid results in the selected cohort. Insufficient cohort is missing comparative context, not poor performance.',
          'Open an athlete’s result to review the original trials before making a recommendation.',
        ],
        'Your interpretation accounts for the source quality, sample size and test definition.',
        'The screenshot intentionally shows a small cohort and an unverified result.',
      ),
    ],
  },
  {
    id: 'scouting-handoff',
    title: 'Report, follow up and finish',
    description: 'Select the report audience and confirm saved work before leaving.',
    steps: [
      step(
        'report-audience',
        'Prepare the correct athlete or staff report',
        'scout-feedback-report',
        'Athlete → Overview → Prepare athlete report',
        [
          'Open Prepare athlete report from the athlete’s Overview.',
          'Read the report heading. Approved athlete feedback contains approved athlete-facing observations; View internal staff report opens a different audience.',
          'Check the athlete, generated date and included content before using Print / save PDF.',
          'Choose the intended printer or Save as PDF in your browser and review the output before sharing through the organizer’s approved process.',
        ],
        'Your report matches the intended audience.',
        'Creating or printing a report does not send it to a family.',
      ),
      step(
        'staff-handoff',
        'Review open work and hand it over',
        'scout-staff-report',
        'Scouting → Reports / Follow-ups / Development',
        [
          'Check reports still In review, follow-ups due and development goals awaiting observation.',
          'After completing the actual work, edit the appropriate record with results and an accurate status. Keep incomplete tasks active.',
          'Give the organizer the unresolved questions, source limitations and next observation dates through your agreed process.',
          'Keep internal staff reports with authorized staff. Use approved athlete feedback for family-facing material.',
        ],
        'The organizer understands the completed evidence and remaining work.',
      ),
      step(
        'unsaved',
        'Resolve unsaved edits before leaving',
        'scout-unsaved',
        'Record editor → Close editor',
        [
          'If closing the editor shows You have unsaved changes, choose Keep editing to review and save the work.',
          'Choose Discard changes only when you intentionally want to abandon those edits.',
          'After saving, wait for confirmation and check the record before navigating away.',
          'If a connection or version warning prevents saving, preserve the observations and ask the organizer for help instead of assuming they were stored.',
        ],
        'You know whether your latest edits were saved or intentionally discarded.',
      ),
      step(
        'signout',
        'Sign out after the handoff',
        'evaluator-sign-out',
        'Workspace → Sign out',
        [
          'Confirm the last record has saved and close any private reports on a shared device.',
          'Choose Sign out and check that the sign-in page appears.',
          'Keep source files, video permissions and exported reports within the agreed audience.',
          'When returning later, use the same account and organization to pick up the next assigned observation.',
        ],
        'Your work is handed over and your account session is closed.',
      ),
    ],
  },
];
