export const FIELD_EXAMPLES = Object.freeze({
  organizationName: 'Badlands Hockey Academy',
  tryoutName: 'U15 Fall Evaluations',
  sport: 'Hockey',
  season: '2026 Fall Season',
  timezone: 'America/Edmonton',
  division: 'U15',
  session: 'Skills Session 1',
  group: 'Forward Group',
  position: 'Forward',
  registrationForm: '2026 Player Registration',
  rubric: 'Skating and Game Sense',
  athleteGivenName: 'Jordan',
  athleteFamilyName: 'Lee',
  guardianName: 'Taylor Lee',
  guardianEmail: 'taylor@example.com',
  guardianPhone: '780-555-0142',
  sports: 'Hockey, Ringette',
  quickTags: 'High compete, Strong skating',
} as const);
